/******************************************************************************
 *
 *               COPYRIGHT (c) 2006-2010 GainSpan Corporation
 *                         All Rights Reserved
 *
 * The source code contained or described herein and all documents
 * related to the source code ("Material") are owned by Gainspan
 * Corporation or its licensors.  Title to the Material remains
 * with Gainspan Corporation or its suppliers and licensors.
 *
 * The Material is protected by worldwide copyright and trade secret
 * laws and treaty provisions. No part of the Material may be used,
 * copied, reproduced, modified, published, uploaded, posted, transmitted,
 * distributed, or disclosed in any way except in accordance with the
 * applicable license agreement.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel, except in accordance with the
 * applicable license agreement.
 *
 * Unless otherwise agreed by Gainspan in writing, you may not remove or
 * alter this notice or any other notice embedded in Materials by Gainspan
 * or Gainspan's suppliers or licensors in any way.
 *
 * $RCSfile: gsn_reg_pwm_op.h,v $
 *
 * Project: GSN APP Software
 *
 * Description:
 *    File generated by reg_build.py from ..\HWdriver\header\xml\PWM-regs.xml
 *
 *
 * Attention : This file must be used with precaution. Somes of its macros can be
 *             non-pertinent. But the original XML file doesn't allow to be pertinent.
 *             So don't include this file as header file. Copy/Paste is preferable.
 *
 ****************************************************************************************
 */

#ifndef _REG_PWM_MAC_H
#define _REG_PWM_MAC_H

/***************************************************
 *
 *             PWM
 *
 ***************************************************/


/*
 *  PWM_PWMCR register macros
 ****************************************************************************************
 */
#define PWM_PWMCR_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCR))
#define PWM_PWMCR_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCR, (value))
#define PWM_PWMCR_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCR, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCR) | (value))
#define PWM_PWMCR_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCR, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCR) & (~(value)))

/*
 *  PWM_CLKFREQ bit field macros
 ****************************************************************************************
 */
#define PWM_CLKFREQ_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_CLKFREQ)
#define PWM_CLKFREQ_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_CLKFREQ, 1)
#define PWM_CLKFREQ_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_CLKFREQ, 0)

/*
 *  PWM_SCLS bit field macros
 ****************************************************************************************
 */
#define PWM_SCLS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_SCLS)
#define PWM_SCLS_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_SCLS, 1)
#define PWM_SCLS_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_SCLS, 0)

/*
 *  PWM_SEN bit field macros
 ****************************************************************************************
 */
#define PWM_SEN_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_SEN)
#define PWM_SEN_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_SEN, 1)
#define PWM_SEN_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_SEN, 0)

/*
 *  PWM_POL2 bit field macros
 ****************************************************************************************
 */
#define PWM_POL2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_POL2)
#define PWM_POL2_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_POL2, 1)
#define PWM_POL2_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_POL2, 0)

/*
 *  PWM_CLS2 bit field macros
 ****************************************************************************************
 */
#define PWM_CLS2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_CLS2)
#define PWM_CLS2_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_CLS2, 1)
#define PWM_CLS2_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_CLS2, 0)

/*
 *  PWM_EN2 bit field macros
 ****************************************************************************************
 */
#define PWM_EN2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_EN2)
#define PWM_EN2_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_EN2, 1)
#define PWM_EN2_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_EN2, 0)

/*
 *  PWM_POL1 bit field macros
 ****************************************************************************************
 */
#define PWM_POL1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_POL1)
#define PWM_POL1_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_POL1, 1)
#define PWM_POL1_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_POL1, 0)

/*
 *  PWM_CLS1 bit field macros
 ****************************************************************************************
 */
#define PWM_CLS1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_CLS1)
#define PWM_CLS1_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_CLS1, 1)
#define PWM_CLS1_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_CLS1, 0)

/*
 *  PWM_EN1 bit field macros
 ****************************************************************************************
 */
#define PWM_EN1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_EN1)
#define PWM_EN1_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_EN1, 1)
#define PWM_EN1_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_EN1, 0)

/*
 *  PWM_POL0 bit field macros
 ****************************************************************************************
 */
#define PWM_POL0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_POL0)
#define PWM_POL0_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_POL0, 1)
#define PWM_POL0_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_POL0, 0)

/*
 *  PWM_CLS0 bit field macros
 ****************************************************************************************
 */
#define PWM_CLS0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_CLS0)
#define PWM_CLS0_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_CLS0, 1)
#define PWM_CLS0_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_CLS0, 0)

/*
 *  PWM_EN0 bit field macros
 ****************************************************************************************
 */
#define PWM_EN0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_EN0)
#define PWM_EN0_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_EN0, 1)
#define PWM_EN0_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_EN0, 0)


/*
 *  PWM_PWMCPS register macros
 ****************************************************************************************
 */
#define PWM_PWMCPS_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCPS))
#define PWM_PWMCPS_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCPS, (value))
#define PWM_PWMCPS_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCPS, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCPS) | (value))
#define PWM_PWMCPS_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCPS, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCPS) & (~(value)))

/*
 *  PWM_CPS bit field macros
 ****************************************************************************************
 */
#define PWM_CPS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_CPS)
#define PWM_CPS_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, PWM_CPS, (value))


/*
 *  PWM_PWMDCR register macros
 ****************************************************************************************
 */
#define PWM_PWMDCR_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMDCR))
#define PWM_PWMDCR_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMDCR, (value))
#define PWM_PWMDCR_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMDCR, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMDCR) | (value))
#define PWM_PWMDCR_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMDCR, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMDCR) & (~(value)))

/*
 *  PWM_PDS1 bit field macros
 ****************************************************************************************
 */
#define PWM_PDS1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_PDS1)
#define PWM_PDS1_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, PWM_PDS1, (value))

/*
 *  PWM_PDS0 bit field macros
 ****************************************************************************************
 */
#define PWM_PDS0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_PDS0)
#define PWM_PDS0_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, PWM_PDS0, (value))


/*
 *  PWM_PWMID register macros
 ****************************************************************************************
 */
#define PWM_PWMID_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMID))

/*
 *  PWM_ID bit field macros
 ****************************************************************************************
 */
#define PWM_ID_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ID)


/*
 *  PWM_PWMCCR0 register macros
 ****************************************************************************************
 */
#define PWM_PWMCCR0_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR0))
#define PWM_PWMCCR0_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR0, (value))
#define PWM_PWMCCR0_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR0, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR0) | (value))
#define PWM_PWMCCR0_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR0, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR0) & (~(value)))

/*
 *  PWM_ONCNT bit field macros
 ****************************************************************************************
 */
#define PWM_ONCNT_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONCNT)
#define PWM_ONCNT_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, PWM_ONCNT, (value))

/*
 *  PWM_OFFCNT bit field macros
 ****************************************************************************************
 */
#define PWM_OFFCNT_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFCNT)
#define PWM_OFFCNT_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFCNT, (value))


/*
 *  PWM_PWMCCR1 register macros
 ****************************************************************************************
 */
#define PWM_PWMCCR1_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR1))
#define PWM_PWMCCR1_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR1, (value))
#define PWM_PWMCCR1_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR1, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR1) | (value))
#define PWM_PWMCCR1_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR1, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR1) & (~(value)))


/*
 *  PWM_PWMCCR2 register macros
 ****************************************************************************************
 */
#define PWM_PWMCCR2_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR2))
#define PWM_PWMCCR2_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR2, (value))
#define PWM_PWMCCR2_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR2, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR2) | (value))
#define PWM_PWMCCR2_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR2, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCCR2) & (~(value)))


/*
 *  PWM_PWMCST0 register macros
 ****************************************************************************************
 */
#define PWM_PWMCST0_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCST0))

/*
 *  PWM_CNTST bit field macros
 ****************************************************************************************
 */
#define PWM_CNTST_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_CNTST)

/*
 *  PWM_CNTVAL bit field macros
 ****************************************************************************************
 */
#define PWM_CNTVAL_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_CNTVAL)


/*
 *  PWM_PWMCST1 register macros
 ****************************************************************************************
 */
#define PWM_PWMCST1_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCST1))


/*
 *  PWM_PWMCST2 register macros
 ****************************************************************************************
 */
#define PWM_PWMCST2_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMCST2))


/*
 *  PWM_PWMIS register macros
 ****************************************************************************************
 */
#define PWM_PWMIS_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIS))

/*
 *  PWM_OFFIS2 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFIS2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFIS2)

/*
 *  PWM_ONIS2 bit field macros
 ****************************************************************************************
 */
#define PWM_ONIS2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONIS2)

/*
 *  PWM_OFFIS1 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFIS1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFIS1)

/*
 *  PWM_ONIS1 bit field macros
 ****************************************************************************************
 */
#define PWM_ONIS1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONIS1)

/*
 *  PWM_OFFIS0 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFIS0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFIS0)

/*
 *  PWM_ONIS0 bit field macros
 ****************************************************************************************
 */
#define PWM_ONIS0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONIS0)


/*
 *  PWM_PWMRIS register macros
 ****************************************************************************************
 */
#define PWM_PWMRIS_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMRIS))

/*
 *  PWM_OFFRIS2 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFRIS2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFRIS2)

/*
 *  PWM_ONRIS2 bit field macros
 ****************************************************************************************
 */
#define PWM_ONRIS2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONRIS2)

/*
 *  PWM_OFFRIS1 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFRIS1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFRIS1)

/*
 *  PWM_ONRIS1 bit field macros
 ****************************************************************************************
 */
#define PWM_ONRIS1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONRIS1)

/*
 *  PWM_OFFRIS0 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFRIS0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFRIS0)

/*
 *  PWM_ONRIS0 bit field macros
 ****************************************************************************************
 */
#define PWM_ONRIS0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONRIS0)


/*
 *  PWM_PWMIM register macros
 ****************************************************************************************
 */
#define PWM_PWMIM_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIM))
#define PWM_PWMIM_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIM, (value))
#define PWM_PWMIM_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIM, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIM) | (value))
#define PWM_PWMIM_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIM, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIM) & (~(value)))

/*
 *  PWM_OFFIM2 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFIM2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFIM2)
#define PWM_OFFIM2_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIM2, 1)
#define PWM_OFFIM2_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIM2, 0)

/*
 *  PWM_ONIM2 bit field macros
 ****************************************************************************************
 */
#define PWM_ONIM2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONIM2)
#define PWM_ONIM2_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIM2, 1)
#define PWM_ONIM2_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIM2, 0)

/*
 *  PWM_OFFIM1 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFIM1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFIM1)
#define PWM_OFFIM1_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIM1, 1)
#define PWM_OFFIM1_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIM1, 0)

/*
 *  PWM_ONIM1 bit field macros
 ****************************************************************************************
 */
#define PWM_ONIM1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONIM1)
#define PWM_ONIM1_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIM1, 1)
#define PWM_ONIM1_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIM1, 0)

/*
 *  PWM_OFFIM0 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFIM0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFIM0)
#define PWM_OFFIM0_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIM0, 1)
#define PWM_OFFIM0_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIM0, 0)

/*
 *  PWM_ONIM0 bit field macros
 ****************************************************************************************
 */
#define PWM_ONIM0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONIM0)
#define PWM_ONIM0_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIM0, 1)
#define PWM_ONIM0_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIM0, 0)


/*
 *  PWM_PWMIC register macros
 ****************************************************************************************
 */
#define PWM_PWMIC_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIC))
#define PWM_PWMIC_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIC, (value))
#define PWM_PWMIC_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIC, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIC) | (value))
#define PWM_PWMIC_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIC, GET_WORD_EXCLUSIVE_BITFIELD(addr, PWM_PWMIC) & (~(value)))

/*
 *  PWM_OFFIC2 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFIC2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFIC2)
#define PWM_OFFIC2_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIC2, 1)
#define PWM_OFFIC2_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIC2, 0)

/*
 *  PWM_ONIC2 bit field macros
 ****************************************************************************************
 */
#define PWM_ONIC2_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONIC2)
#define PWM_ONIC2_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIC2, 1)
#define PWM_ONIC2_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIC2, 0)

/*
 *  PWM_OFFIC1 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFIC1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFIC1)
#define PWM_OFFIC1_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIC1, 1)
#define PWM_OFFIC1_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIC1, 0)

/*
 *  PWM_ONIC1 bit field macros
 ****************************************************************************************
 */
#define PWM_ONIC1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONIC1)
#define PWM_ONIC1_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIC1, 1)
#define PWM_ONIC1_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIC1, 0)

/*
 *  PWM_OFFIC0 bit field macros
 ****************************************************************************************
 */
#define PWM_OFFIC0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_OFFIC0)
#define PWM_OFFIC0_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIC0, 1)
#define PWM_OFFIC0_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_OFFIC0, 0)

/*
 *  PWM_ONIC0 bit field macros
 ****************************************************************************************
 */
#define PWM_ONIC0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, PWM_ONIC0)
#define PWM_ONIC0_SET(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIC0, 1)
#define PWM_ONIC0_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, PWM_ONIC0, 0)

#endif
