/******************************************************************************
 *
 *               COPYRIGHT (c) 2006-2010 GainSpan Corporation
 *                         All Rights Reserved
 *
 * The source code contained or described herein and all documents
 * related to the source code ("Material") are owned by Gainspan
 * Corporation or its licensors.  Title to the Material remains
 * with Gainspan Corporation or its suppliers and licensors.
 *
 * The Material is protected by worldwide copyright and trade secret
 * laws and treaty provisions. No part of the Material may be used,
 * copied, reproduced, modified, published, uploaded, posted, transmitted,
 * distributed, or disclosed in any way except in accordance with the
 * applicable license agreement.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel, except in accordance with the
 * applicable license agreement.
 *
 * Unless otherwise agreed by Gainspan in writing, you may not remove or
 * alter this notice or any other notice embedded in Materials by Gainspan
 * or Gainspan's suppliers or licensors in any way.
 *
 * $RCSfile: gsn_reg_pwm_spec.h,v $
 *
 * Project: GSN APP Software
 *
 * Description:
 *    File generated by reg_build.py from ..\HWdriver\header\xml\PWM-regs.xml
 *
 *
 * Attention : This file must be used with precaution. Somes of its macros can be
 *             non-pertinent. But the original XML file doesn't allow to be pertinent.
 *             So don't include this file as header file. Copy/Paste is preferable.
 *
 ****************************************************************************************
 */

#ifndef _REG_PWM_H
#define _REG_PWM_H

/***************************************************
 *
 *             PWM
 *
 ***************************************************/


/*
 *  COMMON_PWM instance offsets
 ****************************************************************************************
 */
#define COMMON_PWM 0x40100000


/*
 *  PWM_PWMCR register defines
 ****************************************************************************************
 */
#define PWM_PWMCR_OFFSETADDRESS        0x00000000  /* RW */
#define PWM_PWMCR_BITOFFSET            0
#define PWM_PWMCR_BITFIELDSIZE         32
#define PWM_PWMCR_BITMASK              0xFFFFFFFF
#define PWM_PWMCR_INIT                 0x00000000
/*
 *  PWM_CLKFREQ bit field defines
 ****************************************************************************************
 */
#define PWM_CLKFREQ_OFFSETADDRESS               PWM_PWMCR_OFFSETADDRESS
#define PWM_CLKFREQ_BITOFFSET                   16
#define PWM_CLKFREQ_BITFIELDSIZE                1
#define PWM_CLKFREQ_BITMASK                     0x00010000
#define PWM_CLKFREQ_INIT                        0x0
/*
 *  PWM_SCLS bit field defines
 ****************************************************************************************
 */
#define PWM_SCLS_OFFSETADDRESS                  PWM_PWMCR_OFFSETADDRESS
#define PWM_SCLS_BITOFFSET                      13
#define PWM_SCLS_BITFIELDSIZE                   1
#define PWM_SCLS_BITMASK                        0x00002000
#define PWM_SCLS_INIT                           0x0
/*
 *  PWM_SEN bit field defines
 ****************************************************************************************
 */
#define PWM_SEN_OFFSETADDRESS                   PWM_PWMCR_OFFSETADDRESS
#define PWM_SEN_BITOFFSET                      12
#define PWM_SEN_BITFIELDSIZE                    1
#define PWM_SEN_BITMASK                         0x00001000
#define PWM_SEN_INIT                            0x0
/*
 *  PWM_POL2 bit field defines
 ****************************************************************************************
 */
#define PWM_POL2_OFFSETADDRESS                  PWM_PWMCR_OFFSETADDRESS
#define PWM_POL2_BITOFFSET                     10
#define PWM_POL2_BITFIELDSIZE                   1
#define PWM_POL2_BITMASK                        0x00000400
#define PWM_POL2_INIT                           0x0
/*
 *  PWM_CLS2 bit field defines
 ****************************************************************************************
 */
#define PWM_CLS2_OFFSETADDRESS                  PWM_PWMCR_OFFSETADDRESS
#define PWM_CLS2_BITOFFSET                      9
#define PWM_CLS2_BITFIELDSIZE                   1
#define PWM_CLS2_BITMASK                        0x00000200
#define PWM_CLS2_INIT                           0x0
/*
 *  PWM_EN2 bit field defines
 ****************************************************************************************
 */
#define PWM_EN2_OFFSETADDRESS                   PWM_PWMCR_OFFSETADDRESS
#define PWM_EN2_BITOFFSET                       8
#define PWM_EN2_BITFIELDSIZE                    1
#define PWM_EN2_BITMASK                         0x00000100
#define PWM_EN2_INIT                            0x0
/*
 *  PWM_POL1 bit field defines
 ****************************************************************************************
 */
#define PWM_POL1_OFFSETADDRESS                  PWM_PWMCR_OFFSETADDRESS
#define PWM_POL1_BITOFFSET                      6
#define PWM_POL1_BITFIELDSIZE                   1
#define PWM_POL1_BITMASK                        0x00000040
#define PWM_POL1_INIT                           0x0
/*
 *  PWM_CLS1 bit field defines
 ****************************************************************************************
 */
#define PWM_CLS1_OFFSETADDRESS                  PWM_PWMCR_OFFSETADDRESS
#define PWM_CLS1_BITOFFSET                      5
#define PWM_CLS1_BITFIELDSIZE                   1
#define PWM_CLS1_BITMASK                        0x00000020
#define PWM_CLS1_INIT                           0x0
/*
 *  PWM_EN1 bit field defines
 ****************************************************************************************
 */
#define PWM_EN1_OFFSETADDRESS                   PWM_PWMCR_OFFSETADDRESS
#define PWM_EN1_BITOFFSET                       4
#define PWM_EN1_BITFIELDSIZE                    1
#define PWM_EN1_BITMASK                         0x00000010
#define PWM_EN1_INIT                            0x0
/*
 *  PWM_POL0 bit field defines
 ****************************************************************************************
 */
#define PWM_POL0_OFFSETADDRESS                  PWM_PWMCR_OFFSETADDRESS
#define PWM_POL0_BITOFFSET                      2
#define PWM_POL0_BITFIELDSIZE                   1
#define PWM_POL0_BITMASK                        0x00000004
#define PWM_POL0_INIT                           0x0
/*
 *  PWM_CLS0 bit field defines
 ****************************************************************************************
 */
#define PWM_CLS0_OFFSETADDRESS                  PWM_PWMCR_OFFSETADDRESS
#define PWM_CLS0_BITOFFSET                      1
#define PWM_CLS0_BITFIELDSIZE                   1
#define PWM_CLS0_BITMASK                        0x00000002
#define PWM_CLS0_INIT                           0x0
/*
 *  PWM_EN0 bit field defines
 ****************************************************************************************
 */
#define PWM_EN0_OFFSETADDRESS                   PWM_PWMCR_OFFSETADDRESS
#define PWM_EN0_BITOFFSET                       0
#define PWM_EN0_BITFIELDSIZE                    1
#define PWM_EN0_BITMASK                         0x00000001
#define PWM_EN0_INIT                            0x0

/*
 *  PWM_PWMCPS register defines
 ****************************************************************************************
 */
#define PWM_PWMCPS_OFFSETADDRESS       0x00000004  /* RW */
#define PWM_PWMCPS_BITOFFSET           0
#define PWM_PWMCPS_BITFIELDSIZE        32
#define PWM_PWMCPS_BITMASK             0xFFFFFFFF
#define PWM_PWMCPS_INIT                0x00000000
/*
 *  PWM_CPS bit field defines
 ****************************************************************************************
 */
#define PWM_CPS_OFFSETADDRESS                   PWM_PWMCPS_OFFSETADDRESS
#define PWM_CPS_BITOFFSET                       0
#define PWM_CPS_BITFIELDSIZE                    6
#define PWM_CPS_BITMASK                         0x0000003f
#define PWM_CPS_INIT                            0x0

/*
 *  PWM_PWMDCR register defines
 ****************************************************************************************
 */
#define PWM_PWMDCR_OFFSETADDRESS       0x00000008  /* RW */
#define PWM_PWMDCR_BITOFFSET           0
#define PWM_PWMDCR_BITFIELDSIZE        32
#define PWM_PWMDCR_BITMASK             0xFFFFFFFF
#define PWM_PWMDCR_INIT                0x00000000
/*
 *  PWM_PDS1 bit field defines
 ****************************************************************************************
 */
#define PWM_PDS1_OFFSETADDRESS                  PWM_PWMDCR_OFFSETADDRESS
#define PWM_PDS1_BITOFFSET                     16
#define PWM_PDS1_BITFIELDSIZE                  16
#define PWM_PDS1_BITMASK                        0xffff0000
#define PWM_PDS1_INIT                           0x0
/*
 *  PWM_PDS0 bit field defines
 ****************************************************************************************
 */
#define PWM_PDS0_OFFSETADDRESS                  PWM_PWMDCR_OFFSETADDRESS
#define PWM_PDS0_BITOFFSET                      0
#define PWM_PDS0_BITFIELDSIZE                  16
#define PWM_PDS0_BITMASK                        0x0000ffff
#define PWM_PDS0_INIT                           0x0

/*
 *  PWM_PWMID register defines
 ****************************************************************************************
 */
#define PWM_PWMID_OFFSETADDRESS        0x0000000c  /* R */
#define PWM_PWMID_BITOFFSET            0
#define PWM_PWMID_BITFIELDSIZE         32
#define PWM_PWMID_BITMASK              0xFFFFFFFF
#define PWM_PWMID_INIT                 0x00000000
/*
 *  PWM_ID bit field defines
 ****************************************************************************************
 */
#define PWM_ID_OFFSETADDRESS                    PWM_PWMID_OFFSETADDRESS
#define PWM_ID_BITOFFSET                        0
#define PWM_ID_BITFIELDSIZE                    32
#define PWM_ID_BITMASK                          0xffffffff
#define PWM_ID_INIT                             0x0

/*
 *  PWM_PWMCCR0 register defines
 ****************************************************************************************
 */
#define PWM_PWMCCR0_OFFSETADDRESS      0x00000010  /* RW */
#define PWM_PWMCCR0_BITOFFSET          0
#define PWM_PWMCCR0_BITFIELDSIZE       32
#define PWM_PWMCCR0_BITMASK            0xFFFFFFFF
#define PWM_PWMCCR0_INIT               0x00000000
/*
 *  PWM_ONCNT bit field defines
 ****************************************************************************************
 */
#define PWM_ONCNT_OFFSETADDRESS                 PWM_PWMCCR0_OFFSETADDRESS
#define PWM_ONCNT_BITOFFSET                    16
#define PWM_ONCNT_BITFIELDSIZE                 16
#define PWM_ONCNT_BITMASK                       0xffff0000
#define PWM_ONCNT_INIT                          0x0
/*
 *  PWM_OFFCNT bit field defines
 ****************************************************************************************
 */
#define PWM_OFFCNT_OFFSETADDRESS                PWM_PWMCCR0_OFFSETADDRESS
#define PWM_OFFCNT_BITOFFSET                    0
#define PWM_OFFCNT_BITFIELDSIZE                16
#define PWM_OFFCNT_BITMASK                      0x0000ffff
#define PWM_OFFCNT_INIT                         0x0

/*
 *  PWM_PWMCCR1 register defines
 ****************************************************************************************
 */
#define PWM_PWMCCR1_OFFSETADDRESS      0x00000014  /* RW */
#define PWM_PWMCCR1_BITOFFSET          0
#define PWM_PWMCCR1_BITFIELDSIZE       32
#define PWM_PWMCCR1_BITMASK            0xFFFFFFFF
#define PWM_PWMCCR1_INIT               0x00000000

/*
 *  PWM_PWMCCR2 register defines
 ****************************************************************************************
 */
#define PWM_PWMCCR2_OFFSETADDRESS      0x00000018  /* RW */
#define PWM_PWMCCR2_BITOFFSET          0
#define PWM_PWMCCR2_BITFIELDSIZE       32
#define PWM_PWMCCR2_BITMASK            0xFFFFFFFF
#define PWM_PWMCCR2_INIT               0x00000000

/*
 *  PWM_PWMCST0 register defines
 ****************************************************************************************
 */
#define PWM_PWMCST0_OFFSETADDRESS      0x00000020  /* R */
#define PWM_PWMCST0_BITOFFSET          0
#define PWM_PWMCST0_BITFIELDSIZE       32
#define PWM_PWMCST0_BITMASK            0xFFFFFFFF
#define PWM_PWMCST0_INIT               0x00000000
/*
 *  PWM_CNTST bit field defines
 ****************************************************************************************
 */
#define PWM_CNTST_OFFSETADDRESS                 PWM_PWMCST0_OFFSETADDRESS
#define PWM_CNTST_BITOFFSET                    16
#define PWM_CNTST_BITFIELDSIZE                  1
#define PWM_CNTST_BITMASK                       0x00010000
#define PWM_CNTST_INIT                          0x0
/*
 *  PWM_CNTVAL bit field defines
 ****************************************************************************************
 */
#define PWM_CNTVAL_OFFSETADDRESS                PWM_PWMCST0_OFFSETADDRESS
#define PWM_CNTVAL_BITOFFSET                    0
#define PWM_CNTVAL_BITFIELDSIZE                16
#define PWM_CNTVAL_BITMASK                      0x0000ffff
#define PWM_CNTVAL_INIT                         0x0

/*
 *  PWM_PWMCST1 register defines
 ****************************************************************************************
 */
#define PWM_PWMCST1_OFFSETADDRESS      0x00000024  /* R  */
#define PWM_PWMCST1_BITOFFSET          0
#define PWM_PWMCST1_BITFIELDSIZE       32
#define PWM_PWMCST1_BITMASK            0xFFFFFFFF
#define PWM_PWMCST1_INIT               0x00000000

/*
 *  PWM_PWMCST2 register defines
 ****************************************************************************************
 */
#define PWM_PWMCST2_OFFSETADDRESS      0x00000028  /* R  */
#define PWM_PWMCST2_BITOFFSET          0
#define PWM_PWMCST2_BITFIELDSIZE       32
#define PWM_PWMCST2_BITMASK            0xFFFFFFFF
#define PWM_PWMCST2_INIT               0x00000000

/*
 *  PWM_PWMIS register defines
 ****************************************************************************************
 */
#define PWM_PWMIS_OFFSETADDRESS        0x00000030  /* R */
#define PWM_PWMIS_BITOFFSET            0
#define PWM_PWMIS_BITFIELDSIZE         32
#define PWM_PWMIS_BITMASK              0xFFFFFFFF
#define PWM_PWMIS_INIT                 0x00000000
/*
 *  PWM_OFFIS2 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFIS2_OFFSETADDRESS                PWM_PWMIS_OFFSETADDRESS
#define PWM_OFFIS2_BITOFFSET                    9
#define PWM_OFFIS2_BITFIELDSIZE                 1
#define PWM_OFFIS2_BITMASK                      0x00000200
#define PWM_OFFIS2_INIT                         0x0
/*
 *  PWM_ONIS2 bit field defines
 ****************************************************************************************
 */
#define PWM_ONIS2_OFFSETADDRESS                 PWM_PWMIS_OFFSETADDRESS
#define PWM_ONIS2_BITOFFSET                     8
#define PWM_ONIS2_BITFIELDSIZE                  1
#define PWM_ONIS2_BITMASK                       0x00000100
#define PWM_ONIS2_INIT                          0x0
/*
 *  PWM_OFFIS1 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFIS1_OFFSETADDRESS                PWM_PWMIS_OFFSETADDRESS
#define PWM_OFFIS1_BITOFFSET                    5
#define PWM_OFFIS1_BITFIELDSIZE                 1
#define PWM_OFFIS1_BITMASK                      0x00000020
#define PWM_OFFIS1_INIT                         0x0
/*
 *  PWM_ONIS1 bit field defines
 ****************************************************************************************
 */
#define PWM_ONIS1_OFFSETADDRESS                 PWM_PWMIS_OFFSETADDRESS
#define PWM_ONIS1_BITOFFSET                     4
#define PWM_ONIS1_BITFIELDSIZE                  1
#define PWM_ONIS1_BITMASK                       0x00000010
#define PWM_ONIS1_INIT                          0x0
/*
 *  PWM_OFFIS0 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFIS0_OFFSETADDRESS                PWM_PWMIS_OFFSETADDRESS
#define PWM_OFFIS0_BITOFFSET                    1
#define PWM_OFFIS0_BITFIELDSIZE                 1
#define PWM_OFFIS0_BITMASK                      0x00000002
#define PWM_OFFIS0_INIT                         0x0
/*
 *  PWM_ONIS0 bit field defines
 ****************************************************************************************
 */
#define PWM_ONIS0_OFFSETADDRESS                 PWM_PWMIS_OFFSETADDRESS
#define PWM_ONIS0_BITOFFSET                     0
#define PWM_ONIS0_BITFIELDSIZE                  1
#define PWM_ONIS0_BITMASK                       0x00000001
#define PWM_ONIS0_INIT                          0x0

/*
 *  PWM_PWMRIS register defines
 ****************************************************************************************
 */
#define PWM_PWMRIS_OFFSETADDRESS       0x00000034  /* R */
#define PWM_PWMRIS_BITOFFSET           0
#define PWM_PWMRIS_BITFIELDSIZE        32
#define PWM_PWMRIS_BITMASK             0xFFFFFFFF
#define PWM_PWMRIS_INIT                0x00000000
/*
 *  PWM_OFFRIS2 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFRIS2_OFFSETADDRESS               PWM_PWMRIS_OFFSETADDRESS
#define PWM_OFFRIS2_BITOFFSET                   9
#define PWM_OFFRIS2_BITFIELDSIZE                1
#define PWM_OFFRIS2_BITMASK                     0x00000200
#define PWM_OFFRIS2_INIT                        0x0
/*
 *  PWM_ONRIS2 bit field defines
 ****************************************************************************************
 */
#define PWM_ONRIS2_OFFSETADDRESS                PWM_PWMRIS_OFFSETADDRESS
#define PWM_ONRIS2_BITOFFSET                    8
#define PWM_ONRIS2_BITFIELDSIZE                 1
#define PWM_ONRIS2_BITMASK                      0x00000100
#define PWM_ONRIS2_INIT                         0x0
/*
 *  PWM_OFFRIS1 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFRIS1_OFFSETADDRESS               PWM_PWMRIS_OFFSETADDRESS
#define PWM_OFFRIS1_BITOFFSET                   5
#define PWM_OFFRIS1_BITFIELDSIZE                1
#define PWM_OFFRIS1_BITMASK                     0x00000020
#define PWM_OFFRIS1_INIT                        0x0
/*
 *  PWM_ONRIS1 bit field defines
 ****************************************************************************************
 */
#define PWM_ONRIS1_OFFSETADDRESS                PWM_PWMRIS_OFFSETADDRESS
#define PWM_ONRIS1_BITOFFSET                    4
#define PWM_ONRIS1_BITFIELDSIZE                 1
#define PWM_ONRIS1_BITMASK                      0x00000010
#define PWM_ONRIS1_INIT                         0x0
/*
 *  PWM_OFFRIS0 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFRIS0_OFFSETADDRESS               PWM_PWMRIS_OFFSETADDRESS
#define PWM_OFFRIS0_BITOFFSET                   1
#define PWM_OFFRIS0_BITFIELDSIZE                1
#define PWM_OFFRIS0_BITMASK                     0x00000002
#define PWM_OFFRIS0_INIT                        0x0
/*
 *  PWM_ONRIS0 bit field defines
 ****************************************************************************************
 */
#define PWM_ONRIS0_OFFSETADDRESS                PWM_PWMRIS_OFFSETADDRESS
#define PWM_ONRIS0_BITOFFSET                    0
#define PWM_ONRIS0_BITFIELDSIZE                 1
#define PWM_ONRIS0_BITMASK                      0x00000001
#define PWM_ONRIS0_INIT                         0x0

/*
 *  PWM_PWMIM register defines
 ****************************************************************************************
 */
#define PWM_PWMIM_OFFSETADDRESS        0x00000038  /* RW */
#define PWM_PWMIM_BITOFFSET            0
#define PWM_PWMIM_BITFIELDSIZE         32
#define PWM_PWMIM_BITMASK              0xFFFFFFFF
#define PWM_PWMIM_INIT                 0x00000000
/*
 *  PWM_OFFIM2 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFIM2_OFFSETADDRESS                PWM_PWMIM_OFFSETADDRESS
#define PWM_OFFIM2_BITOFFSET                    9
#define PWM_OFFIM2_BITFIELDSIZE                 1
#define PWM_OFFIM2_BITMASK                      0x00000200
#define PWM_OFFIM2_INIT                         0x0
/*
 *  PWM_ONIM2 bit field defines
 ****************************************************************************************
 */
#define PWM_ONIM2_OFFSETADDRESS                 PWM_PWMIM_OFFSETADDRESS
#define PWM_ONIM2_BITOFFSET                     8
#define PWM_ONIM2_BITFIELDSIZE                  1
#define PWM_ONIM2_BITMASK                       0x00000100
#define PWM_ONIM2_INIT                          0x0
/*
 *  PWM_OFFIM1 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFIM1_OFFSETADDRESS                PWM_PWMIM_OFFSETADDRESS
#define PWM_OFFIM1_BITOFFSET                    5
#define PWM_OFFIM1_BITFIELDSIZE                 1
#define PWM_OFFIM1_BITMASK                      0x00000020
#define PWM_OFFIM1_INIT                         0x0
/*
 *  PWM_ONIM1 bit field defines
 ****************************************************************************************
 */
#define PWM_ONIM1_OFFSETADDRESS                 PWM_PWMIM_OFFSETADDRESS
#define PWM_ONIM1_BITOFFSET                     4
#define PWM_ONIM1_BITFIELDSIZE                  1
#define PWM_ONIM1_BITMASK                       0x00000010
#define PWM_ONIM1_INIT                          0x0
/*
 *  PWM_OFFIM0 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFIM0_OFFSETADDRESS                PWM_PWMIM_OFFSETADDRESS
#define PWM_OFFIM0_BITOFFSET                    1
#define PWM_OFFIM0_BITFIELDSIZE                 1
#define PWM_OFFIM0_BITMASK                      0x00000002
#define PWM_OFFIM0_INIT                         0x0
/*
 *  PWM_ONIM0 bit field defines
 ****************************************************************************************
 */
#define PWM_ONIM0_OFFSETADDRESS                 PWM_PWMIM_OFFSETADDRESS
#define PWM_ONIM0_BITOFFSET                     0
#define PWM_ONIM0_BITFIELDSIZE                  1
#define PWM_ONIM0_BITMASK                       0x00000001
#define PWM_ONIM0_INIT                          0x0

/*
 *  PWM_PWMIC register defines
 ****************************************************************************************
 */
#define PWM_PWMIC_OFFSETADDRESS        0x0000003c  /* RW */
#define PWM_PWMIC_BITOFFSET            0
#define PWM_PWMIC_BITFIELDSIZE         32
#define PWM_PWMIC_BITMASK              0xFFFFFFFF
#define PWM_PWMIC_INIT                 0x00000000
/*
 *  PWM_OFFIC2 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFIC2_OFFSETADDRESS                PWM_PWMIC_OFFSETADDRESS
#define PWM_OFFIC2_BITOFFSET                    9
#define PWM_OFFIC2_BITFIELDSIZE                 1
#define PWM_OFFIC2_BITMASK                      0x00000200
#define PWM_OFFIC2_INIT                         0x0
/*
 *  PWM_ONIC2 bit field defines
 ****************************************************************************************
 */
#define PWM_ONIC2_OFFSETADDRESS                 PWM_PWMIC_OFFSETADDRESS
#define PWM_ONIC2_BITOFFSET                     8
#define PWM_ONIC2_BITFIELDSIZE                  1
#define PWM_ONIC2_BITMASK                       0x00000100
#define PWM_ONIC2_INIT                          0x0
/*
 *  PWM_OFFIC1 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFIC1_OFFSETADDRESS                PWM_PWMIC_OFFSETADDRESS
#define PWM_OFFIC1_BITOFFSET                    5
#define PWM_OFFIC1_BITFIELDSIZE                 1
#define PWM_OFFIC1_BITMASK                      0x00000020
#define PWM_OFFIC1_INIT                         0x0
/*
 *  PWM_ONIC1 bit field defines
 ****************************************************************************************
 */
#define PWM_ONIC1_OFFSETADDRESS                 PWM_PWMIC_OFFSETADDRESS
#define PWM_ONIC1_BITOFFSET                     4
#define PWM_ONIC1_BITFIELDSIZE                  1
#define PWM_ONIC1_BITMASK                       0x00000010
#define PWM_ONIC1_INIT                          0x0
/*
 *  PWM_OFFIC0 bit field defines
 ****************************************************************************************
 */
#define PWM_OFFIC0_OFFSETADDRESS                PWM_PWMIC_OFFSETADDRESS
#define PWM_OFFIC0_BITOFFSET                    1
#define PWM_OFFIC0_BITFIELDSIZE                 1
#define PWM_OFFIC0_BITMASK                      0x00000002
#define PWM_OFFIC0_INIT                         0x0
/*
 *  PWM_ONIC0 bit field defines
 ****************************************************************************************
 */
#define PWM_ONIC0_OFFSETADDRESS                 PWM_PWMIC_OFFSETADDRESS
#define PWM_ONIC0_BITOFFSET                     0
#define PWM_ONIC0_BITFIELDSIZE                  1
#define PWM_ONIC0_BITMASK                       0x00000001
#define PWM_ONIC0_INIT                          0x0
#endif
