/*
 ****************************************************************************************
 * reg_i2c.h
 *
 * Copyright (C) NewLogic 2003-2005
 *
 * Project: LPX Software
 *
 * Description:
 *    File generated by reg_build.py from ..\HWdriver\header\xml\reg_i2c.xml
 *
 *
 * Attention : This file must be used with precaution. Somes of its macros can be
 *             non-pertinent. But the original XML file doesn't allow to be pertinent.
 *             So don't include this file as header file. Copy/Paste is preferable.
 *
 ****************************************************************************************
 */

#ifndef _REG_I2C_H
#define _REG_I2C_H

/***************************************************
 *
 *             I2C
 *
 ***************************************************/


/*
 *  COMMON_I2C instance offsets
 ****************************************************************************************
 */
#define COMMON_I2C 0x40090000

/*
 *  I2C_I2CSLAD0 register defines
 ****************************************************************************************
 */
#define I2C_I2CSLAD0_OFFSETADDRESS     0x00000000  /* RW */
#define I2C_I2CSLAD0_BITOFFSET         0
#define I2C_I2CSLAD0_BITFIELDSIZE      8
#define I2C_I2CSLAD0_BITMASK           0xFF
#define I2C_I2CSLAD0_INIT              0x00000000
/*
 *  I2C_SLAD0 bit field defines
 ****************************************************************************************
 */
#define I2C_SLAD0_OFFSETADDRESS                 I2C_I2CSLAD0_OFFSETADDRESS
#define I2C_SLAD0_BITOFFSET                     0
#define I2C_SLAD0_BITFIELDSIZE                  8
#define I2C_SLAD0_BITMASK                       0xff
#define I2C_SLAD0_INIT                          0x0

/*
 *  I2C_I2CSLAD1 register defines
 ****************************************************************************************
 */
#define I2C_I2CSLAD1_OFFSETADDRESS     0x00000004  /* RW */
#define I2C_I2CSLAD1_BITOFFSET         0
#define I2C_I2CSLAD1_BITFIELDSIZE      8
#define I2C_I2CSLAD1_BITMASK           0xFF
#define I2C_I2CSLAD1_INIT              0x00000000
/*
 *  I2C_SLAD1 bit field defines
 ****************************************************************************************
 */
#define I2C_SLAD1_OFFSETADDRESS                 I2C_I2CSLAD1_OFFSETADDRESS
#define I2C_SLAD1_BITOFFSET                     0
#define I2C_SLAD1_BITFIELDSIZE                  2
#define I2C_SLAD1_BITMASK                       0x00000003
#define I2C_SLAD1_INIT                          0x0
/*
 *  I2C_ADMOD bit field defines
 ****************************************************************************************
 */
#define I2C_ADMOD_OFFSETADDRESS                 I2C_I2CSLAD1_OFFSETADDRESS
#define I2C_ADMOD_BITOFFSET                     2
#define I2C_ADMOD_BITFIELDSIZE                  1
#define I2C_ADMOD_BITMASK                       0x00000004
#define I2C_ADMOD_INIT                          0x0
/*
 *  I2C_MNS bit field defines
 ****************************************************************************************
 */
#define I2C_MNS_OFFSETADDRESS                   I2C_I2CSLAD1_OFFSETADDRESS
#define I2C_MNS_BITOFFSET                       3
#define I2C_MNS_BITFIELDSIZE                    1
#define I2C_MNS_BITMASK                         0x00000008
#define I2C_MNS_INIT                            0x0
/*
 *  I2C_HSE bit field defines
 ****************************************************************************************
 */
#define I2C_HSE_OFFSETADDRESS                   I2C_I2CSLAD1_OFFSETADDRESS
#define I2C_HSE_BITOFFSET                       4
#define I2C_HSE_BITFIELDSIZE                    1
#define I2C_HSE_BITMASK                         0x00000010
#define I2C_HSE_INIT                            0x0

/*
 *  I2C_I2CIER register defines
 ****************************************************************************************
 */
#define I2C_I2CIER_OFFSETADDRESS       0x00000008  /* RW */
#define I2C_I2CIER_BITOFFSET           0
#define I2C_I2CIER_BITFIELDSIZE        8
#define I2C_I2CIER_BITMASK             0x000000FF
#define I2C_I2CIER_INIT                0x00000000
/*
 *  I2C_EFEI bit field defines
 ****************************************************************************************
 */
#define I2C_EFEI_OFFSETADDRESS                  I2C_I2CIER_OFFSETADDRESS
#define I2C_EFEI_BITOFFSET                      0
#define I2C_EFEI_BITFIELDSIZE                   1
#define I2C_EFEI_BITMASK                        0x00000001
#define I2C_EFEI_INIT                           0x0
/*
 *  I2C_EBI bit field defines
 ****************************************************************************************
 */
#define I2C_EBI_OFFSETADDRESS                   I2C_I2CIER_OFFSETADDRESS
#define I2C_EBI_BITOFFSET                       1
#define I2C_EBI_BITFIELDSIZE                    1
#define I2C_EBI_BITMASK                         0x00000002
#define I2C_EBI_INIT                            0x0
/*
 *  I2C_EFFI bit field defines
 ****************************************************************************************
 */
#define I2C_EFFI_OFFSETADDRESS                  I2C_I2CIER_OFFSETADDRESS
#define I2C_EFFI_BITOFFSET                      2
#define I2C_EFFI_BITFIELDSIZE                   1
#define I2C_EFFI_BITMASK                        0x00000004
#define I2C_EFFI_INIT                           0x0
/*
 *  I2C_EOCI bit field defines
 ****************************************************************************************
 */
#define I2C_EOCI_OFFSETADDRESS                  I2C_I2CIER_OFFSETADDRESS
#define I2C_EOCI_BITOFFSET                      4
#define I2C_EOCI_BITFIELDSIZE                   1
#define I2C_EOCI_BITMASK                        0x00000010
#define I2C_EOCI_INIT                           0x0
/*
 *  I2C_ENAEI bit field defines
 ****************************************************************************************
 */
#define I2C_ENAEI_OFFSETADDRESS                 I2C_I2CIER_OFFSETADDRESS
#define I2C_ENAEI_BITOFFSET                     5
#define I2C_ENAEI_BITFIELDSIZE                  1
#define I2C_ENAEI_BITMASK                       0x00000020
#define I2C_ENAEI_INIT                          0x0
/*
 *  I2C_AFI bit field defines
 ****************************************************************************************
 */
#define I2C_EAFI_OFFSETADDRESS                   I2C_I2CIER_OFFSETADDRESS
#define I2C_EAFI_BITOFFSET                       6
#define I2C_EAFI_BITFIELDSIZE                    1
#define I2C_EAFI_BITMASK                         0x00000040
#define I2C_EAFI_INIT                            0x0

/*
 *  I2C_I2CISR register defines
 ****************************************************************************************
 */
#define I2C_I2CISR_OFFSETADDRESS       0x0000000c  /* R */
#define I2C_I2CISR_BITOFFSET           0
#define I2C_I2CISR_BITFIELDSIZE        8
#define I2C_I2CISR_BITMASK             0xFF
#define I2C_I2CISR_INIT                0x00000000
/*
 *  I2C_FEI bit field defines
 ****************************************************************************************
 */
#define I2C_FEI_OFFSETADDRESS                   I2C_I2CISR_OFFSETADDRESS
#define I2C_FEI_BITOFFSET                       0
#define I2C_FEI_BITFIELDSIZE                    1
#define I2C_FEI_BITMASK                         0x00000001
#define I2C_FEI_INIT                            0x0
/*
 *  I2C_BI bit field defines
 ****************************************************************************************
 */
#define I2C_BI_OFFSETADDRESS                    I2C_I2CISR_OFFSETADDRESS
#define I2C_BI_BITOFFSET                        1
#define I2C_BI_BITFIELDSIZE                     1
#define I2C_BI_BITMASK                          0x00000002
#define I2C_BI_INIT                             0x0
/*
 *  I2C_FFI bit field defines
 ****************************************************************************************
 */
#define I2C_FFI_OFFSETADDRESS                   I2C_I2CISR_OFFSETADDRESS
#define I2C_FFI_BITOFFSET                       2
#define I2C_FFI_BITFIELDSIZE                    1
#define I2C_FFI_BITMASK                         0x00000004
#define I2C_FFI_INIT                            0x0
/*
 *  I2C_OCI bit field defines
 ****************************************************************************************
 */
#define I2C_OCI_OFFSETADDRESS                   I2C_I2CISR_OFFSETADDRESS
#define I2C_OCI_BITOFFSET                       4
#define I2C_OCI_BITFIELDSIZE                    1
#define I2C_OCI_BITMASK                         0x00000010
#define I2C_OCI_INIT                            0x0
/*
 *  I2C_NAEI bit field defines
 ****************************************************************************************
 */
#define I2C_NAEI_OFFSETADDRESS                  I2C_I2CISR_OFFSETADDRESS
#define I2C_NAEI_BITOFFSET                      5
#define I2C_NAEI_BITFIELDSIZE                   1
#define I2C_NAEI_BITMASK                        0x00000020
#define I2C_NAEI_INIT                           0x0
/*
 *  I2C_AFI bit field defines
 ****************************************************************************************
 */
#define I2C_AFI_OFFSETADDRESS                   I2C_I2CISR_OFFSETADDRESS
#define I2C_AFI_BITOFFSET                       6
#define I2C_AFI_BITFIELDSIZE                    1
#define I2C_AFI_BITMASK                         0x00000040
#define I2C_AFI_INIT                            0x0

/*
 *  I2C_I2CAPBADDRLSB register defines
 ****************************************************************************************
 */
#define I2C_I2CAPBADDRLSB_OFFSETADDRESS 		0x000000010  /* RW */
#define I2C_I2CAPBADDRLSB_BITOFFSET    			0
#define I2C_I2CAPBADDRLSB_BITFIELDSIZE 			8
#define I2C_I2CAPBADDRLSB_BITMASK      			0xFF
#define I2C_I2CAPBADDRLSB_INIT         			0x00000000
/*
 *   I2C_I2CAPBADDRLSB bit field defines
 ****************************************************************************************
 */
#define I2C_APBADDRLSB_OFFSETADDRESS 		I2C_I2CAPBADDRLSB_OFFSETADDRESS 
#define I2C_APBADDRLSB_BITOFFSET    			0
#define I2C_APBADDRLSB_BITFIELDSIZE 			8
#define I2C_APBADDRLSB_BITMASK      			0xFF
#define I2C_APBADDRLSB_INIT         			0x00000000

/*
 *  I2C_I2CAPBADDRMSB register defines
 ****************************************************************************************
 */
#define I2C_I2CAPBADDRMSB_OFFSETADDRESS 		0x00000014  /* RW */
#define I2C_I2CAPBADDRMSB_BITOFFSET    			0
#define I2C_I2CAPBADDRMSB_BITFIELDSIZE 			8
#define I2C_I2CAPBADDRMSB_BITMASK      			0xFF
#define I2C_I2CAPBADDRMSB_INIT         			0x00000000
/*
 *  I2C_DATA bit field defines
 ****************************************************************************************
 */                 
#define I2C_APBADDRMSB_OFFSETADDRESS 		I2C_I2CAPBADDRMSB_OFFSETADDRESS
#define I2C_APBADDRMSB_BITOFFSET    			0
#define I2C_APBADDRMSB_BITFIELDSIZE 			8
#define I2C_APBADDRMSB_BITMASK      			0xFF
#define I2C_APBADDRMSB_INIT         			0x00000000

/*
 *  I2C_I2CDACNTLSB register defines
 ****************************************************************************************
 */
#define I2C_I2CDACNTLSB_OFFSETADDRESS  			0x00000018  /* RW */
#define I2C_I2CDACNTLSB_BITOFFSET      			0
#define I2C_I2CDACNTLSB_BITFIELDSIZE   			8
#define I2C_I2CDACNTLSB_BITMASK        			0xFF
#define I2C_I2CDACNTLSB_INIT           			0x00000000
/*
 *  I2C_DACNT bit field defines
 ****************************************************************************************
 */
#define I2C_DACNTLSB_OFFSETADDRESS           I2C_I2CDACNTLSB_OFFSETADDRESS
#define I2C_DACNTLSB_BITOFFSET               0
#define I2C_DACNTLSB_BITFIELDSIZE            8
#define I2C_DACNTLSB_BITMASK                 0xFF
#define I2C_DACNTLSB_INIT                    0x00000000

/*
 *  I2C_I2CDATA register defines
 ****************************************************************************************
 */
#define I2C_I2CDATA_OFFSETADDRESS      			0x00000020  /* RW */
#define I2C_I2CDATA_BITOFFSET          			0
#define I2C_I2CDATA_BITFIELDSIZE      		 	8
#define I2C_I2CDATA_BITMASK            			0xFF
#define I2C_I2CDATA_INIT               			0x00000000
/*
 *  I2C_DATA bit field defines
 ****************************************************************************************
 */
#define I2C_DATA_OFFSETADDRESS                  I2C_I2CDATA_OFFSETADDRESS
#define I2C_DATA_BITOFFSET                      0
#define I2C_DATA_BITFIELDSIZE                   8
#define I2C_DATA_BITMASK                        0xFF
#define I2C_DATA_INIT                           0x00

/*
 *  I2C_I2CCR register defines
 ****************************************************************************************
 */
#define I2C_I2CCR_OFFSETADDRESS        0x00000024  /* RW */
#define I2C_I2CCR_BITOFFSET            0
#define I2C_I2CCR_BITFIELDSIZE         8
#define I2C_I2CCR_BITMASK              0xFF
#define I2C_I2CCR_INIT                 0x00000000
/*
 *  I2C_RWOP bit field defines
 ****************************************************************************************
 */
#define I2C_RWOP_OFFSETADDRESS                  I2C_I2CCR_OFFSETADDRESS
#define I2C_RWOP_BITOFFSET                      0
#define I2C_RWOP_BITFIELDSIZE                   1
#define I2C_RWOP_BITMASK                        0x00000001
#define I2C_RWOP_INIT                           0x0
/*
 *  I2C_AOP bit field defines
 ****************************************************************************************
 */
#define I2C_AOP_OFFSETADDRESS                   I2C_I2CCR_OFFSETADDRESS
#define I2C_AOP_BITOFFSET                       1
#define I2C_AOP_BITFIELDSIZE                    1
#define I2C_AOP_BITMASK                         0x00000002
#define I2C_AOP_INIT                            0x0
/*
 *  I2C_BCO bit field defines
 ****************************************************************************************
 */
#define I2C_BCO_OFFSETADDRESS                   I2C_I2CCR_OFFSETADDRESS
#define I2C_BCO_BITOFFSET                       2
#define I2C_BCO_BITFIELDSIZE                    1
#define I2C_BCO_BITMASK                         0x00000004
#define I2C_BCO_INIT                            0x0
/*
 *  I2C_RCAS bit field defines
 ****************************************************************************************
 */
#define I2C_RCAS_OFFSETADDRESS                  I2C_I2CCR_OFFSETADDRESS
#define I2C_RCAS_BITOFFSET                      3
#define I2C_RCAS_BITFIELDSIZE                   1
#define I2C_RCAS_BITMASK                        0x00000008
#define I2C_RCAS_INIT                           0x0
/*
 *  I2C_MAS bit field defines
 ****************************************************************************************
 */
#define I2C_MAS_OFFSETADDRESS                   I2C_I2CCR_OFFSETADDRESS
#define I2C_MAS_BITOFFSET                       4
#define I2C_MAS_BITFIELDSIZE                    1
#define I2C_MAS_BITMASK                         0x00000010
#define I2C_MAS_INIT                            0x0

/*
 *  I2C_I2CADDRLSB register defines
 ****************************************************************************************
 */
#define I2C_I2CADDRLSB_OFFSETADDRESS   0x00000028  /* RW */
#define I2C_I2CADDRLSB_BITOFFSET       0
#define I2C_I2CADDRLSB_BITFIELDSIZE    8
#define I2C_I2CADDRLSB_BITMASK         0xFF
#define I2C_I2CADDRLSB_INIT            0x00000000
/*
 *  I2C_SADDRLSB bit field defines
 ****************************************************************************************
 */
#define I2C_SADDRLSB_OFFSETADDRESS              I2C_I2CADDRLSB_OFFSETADDRESS
#define I2C_SADDRLSB_BITOFFSET                  0
#define I2C_SADDRLSB_BITFIELDSIZE               8
#define I2C_SADDRLSB_BITMASK                    0xff
#define I2C_SADDRLSB_INIT                       0x0

/*
 *  I2C_I2CADDRMSB register defines
 ****************************************************************************************
 */
#define I2C_I2CADDRMSB_OFFSETADDRESS   0x0000002c  /* RW */
#define I2C_I2CADDRMSB_BITOFFSET       0
#define I2C_I2CADDRMSB_BITFIELDSIZE    8
#define I2C_I2CADDRMSB_BITMASK         0xFF
#define I2C_I2CADDRMSB_INIT            0x00000000
/*
 *  I2C_SADDRMSB bit field defines
 ****************************************************************************************
 */
#define I2C_SADDRMSB_OFFSETADDRESS              I2C_I2CADDRMSB_OFFSETADDRESS
#define I2C_SADDRMSB_BITOFFSET                  0
#define I2C_SADDRMSB_BITFIELDSIZE               8
#define I2C_SADDRMSB_BITMASK                    0xff
#define I2C_SADDRMSB_INIT                       0x0

/*
 *  I2C_I2CDACNTR register defines
 ****************************************************************************************
 */
#define I2C_I2CDACNTR_OFFSETADDRESS    0x00000030  /* RW */
#define I2C_I2CDACNTR_BITOFFSET        0
#define I2C_I2CDACNTR_BITFIELDSIZE     8
#define I2C_I2CDACNTR_BITMASK          0xFF
#define I2C_I2CDACNTR_INIT             0x00000000
/*
 *  I2C_SDACNT bit field defines
 ****************************************************************************************
 */
#define I2C_SDACNT_OFFSETADDRESS                I2C_I2CDACNTR_OFFSETADDRESS
#define I2C_SDACNT_BITOFFSET                    0
#define I2C_SDACNT_BITFIELDSIZE                 8
#define I2C_SDACNT_BITMASK                      0xff
#define I2C_SDACNT_INIT                         0x0

/*
 *  I2C_I2CMCR register defines
 ****************************************************************************************
 */
#define I2C_I2CMCR_OFFSETADDRESS       0x00000038  /* RW */
#define I2C_I2CMCR_BITOFFSET           0
#define I2C_I2CMCR_BITFIELDSIZE        8
#define I2C_I2CMCR_BITMASK             0xFF
#define I2C_I2CMCR_INIT                0x00000000
/*
 *  I2C_MCODE bit field defines
 ****************************************************************************************
 */
#define I2C_MCODE_OFFSETADDRESS                 I2C_I2CMCR_OFFSETADDRESS
#define I2C_MCODE_BITOFFSET                     0
#define I2C_MCODE_BITFIELDSIZE                  8
#define I2C_MCODE_BITMASK                       0xff
#define I2C_MCODE_INIT                          0x0

/*
 *  I2C_I2CHCCR register defines
 ****************************************************************************************
 */
#define I2C_I2CHCCR_OFFSETADDRESS      0x0000003c  /* RW */
#define I2C_I2CHCCR_BITOFFSET          0
#define I2C_I2CHCCR_BITFIELDSIZE       8
#define I2C_I2CHCCR_BITMASK            0xFF
#define I2C_I2CHCCR_INIT               0x00000000
/*
 *  I2C_CCOUNT bit field defines
 ****************************************************************************************
 */
#define I2C_CCOUNT_OFFSETADDRESS                I2C_I2CHCCR_OFFSETADDRESS
#define I2C_CCOUNT_BITOFFSET                    0
#define I2C_CCOUNT_BITFIELDSIZE                 8
#define I2C_CCOUNT_BITMASK                      0xff
#define I2C_CCOUNT_INIT                         0x0
#endif
