/*
 ****************************************************************************************
 * reg_sdio.h
 *
 * Copyright (C) NewLogic 2003-2005
 *
 * Project: LPX Software
 *
 * Description:
 *    File generated by reg_build.py from ..\HWdriver\header\xml\reg_sdio.xml
 *
 *
 * Attention : This file must be used with precaution. Somes of its macros can be
 *             non-pertinent. But the original XML file doesn't allow to be pertinent.
 *             So don't include this file as header file. Copy/Paste is preferable.
 *
 ****************************************************************************************
 */

#ifndef _REG_SDIO_H
#define _REG_SDIO_H

/***************************************************
 *
 *             SDIO
 *
 ***************************************************/


/*
 *  COMMON_SDIO instance offsets
 ****************************************************************************************
 */
#define COMMON_SDIO 0x40300000 

/*
 *  SDIO_DATAPORT register defines
 ****************************************************************************************
 */
#define SDIO_DATAPORT_OFFSETADDRESS    0x00000000  /* RW */
#define SDIO_DATAPORT_BITOFFSET        0
#define SDIO_DATAPORT_BITFIELDSIZE     32
#define SDIO_DATAPORT_BITMASK          0xFFFFFFFF
#define SDIO_DATAPORT_INIT             0x00000000
/*
 *  SDIO_DATA bit field defines
 ****************************************************************************************
 */
#define SDIO_DATA_OFFSETADDRESS                 SDIO_DATAPORT_OFFSETADDRESS
#define SDIO_DATA_BITOFFSET                     0
#define SDIO_DATA_BITFIELDSIZE                  32
#define SDIO_DATA_BITMASK                       0xffffffff
#define SDIO_DATA_INIT                          0x0

/*
 *  SDIO_IIR register defines
 ****************************************************************************************
 */
#define SDIO_IIR_OFFSETADDRESS         0x00000004  /* RW */
#define SDIO_IIR_BITOFFSET             0
#define SDIO_IIR_BITFIELDSIZE          32
#define SDIO_IIR_BITMASK               0xFFFFFFFF
#define SDIO_IIR_INIT                  0x00000000
/*
 *  SDIO_DATARDY bit field defines
 ****************************************************************************************
 */
#define SDIO_DATARDY_OFFSETADDRESS              SDIO_IIR_OFFSETADDRESS
#define SDIO_DATARDY_BITOFFSET                  0
#define SDIO_DATARDY_BITFIELDSIZE               1
#define SDIO_DATARDY_BITMASK                    0x00000001
#define SDIO_DATARDY_INIT                       0x0
/*
 *  SDIO_ERROR bit field defines
 ****************************************************************************************
 */
#define SDIO_ERROR_OFFSETADDRESS                SDIO_IIR_OFFSETADDRESS
#define SDIO_ERROR_BITOFFSET                    1
#define SDIO_ERROR_BITFIELDSIZE                 1
#define SDIO_ERROR_BITMASK                      0x00000002
#define SDIO_ERROR_INIT                         0x0

/*
 *  SDIO_CISFUN0ADDREG register defines
 ****************************************************************************************
 */
#define SDIO_CISFUN0ADDREG_OFFSETADDRESS 0x00000008  /* RW */
#define SDIO_CISFUN0ADDREG_BITOFFSET     0
#define SDIO_CISFUN0ADDREG_BITFIELDSIZE  32
#define SDIO_CISFUN0ADDREG_BITMASK       0xFFFFFFFF
#define SDIO_CISFUN0ADDREG_INIT          0x00000000
/*
 *  SDIO_ADDRESS bit field defines
 ****************************************************************************************
 */
#define SDIO_CISFUN0ADDRESS_OFFSETADDRESS              SDIO_CISFUN0ADDREG_OFFSETADDRESS
#define SDIO_CISFUN0ADDRESS_BITOFFSET                  0
#define SDIO_CISFUN0ADDRESS_BITFIELDSIZE               32
#define SDIO_CISFUN0ADDRESS_BITMASK                    0xffffffff
#define SDIO_CISFUN0ADDRESS_INIT                       0x0

/*
 *  SDIO_CISFUN1ADDREG register defines
 ****************************************************************************************
 */
#define SDIO_CISFUN1ADDREG_OFFSETADDRESS 0x0000000c  /* R */
#define SDIO_CISFUN1ADDREG_BITOFFSET     0
#define SDIO_CISFUN1ADDREG_BITFIELDSIZE  32
#define SDIO_CISFUN1ADDREG_BITMASK       0xFFFFFFFF
#define SDIO_CISFUN1ADDREG_INIT          0x00000000
/*
 *  SDIO_ADDRESS bit field defines
 ****************************************************************************************
 */
#define SDIO_CISFUN1ADDRESS_OFFSETADDRESS              SDIO_CISFUN1ADDREG_OFFSETADDRESS
#define SDIO_CISFUN1ADDRESS_BITOFFSET                  0
#define SDIO_CISFUN1ADDRESS_BITFIELDSIZE               32
#define SDIO_CISFUN1ADDRESS_BITMASK                    0xffffffff
#define SDIO_CISFUN1ADDRESS_INIT                       0x0

/*
 *  SDIO_CSAADDREG register defines
 ****************************************************************************************
 */
#define SDIO_CSAADDREG_OFFSETADDRESS   0x00000010  /* RW */
#define SDIO_CSAADDREG_BITOFFSET       0
#define SDIO_CSAADDREG_BITFIELDSIZE    32
#define SDIO_CSAADDREG_BITMASK         0xFFFFFFFF
#define SDIO_CSAADDREG_INIT            0x00000000
/*
 *  SDIO_ADDRESS bit field defines
 ****************************************************************************************
 */
#define SDIO_ADDRESS_OFFSETADDRESS              SDIO_CSAADDREG_OFFSETADDRESS
#define SDIO_ADDRESS_BITOFFSET                  0
#define SDIO_ADDRESS_BITFIELDSIZE               32
#define SDIO_ADDRESS_BITMASK                    0xffffffff
#define SDIO_ADDRESS_INIT                       0x0

/*
 *  SDIO_RDADDREG register defines
 ****************************************************************************************
 */
#define SDIO_RDADDREG_OFFSETADDRESS    0x00000014  /* RW */
#define SDIO_RDADDREG_BITOFFSET        0
#define SDIO_RDADDREG_BITFIELDSIZE     32
#define SDIO_RDADDREG_BITMASK          0xFFFFFFFF
#define SDIO_RDADDREG_INIT             0x00000000
/*
 *  SDIO_ADDRESS bit field defines
 ****************************************************************************************
 */
#define SDIO_RDADDRESS_OFFSETADDRESS              SDIO_RDADDREG_OFFSETADDRESS
#define SDIO_RDADDRESS_BITOFFSET                  0
#define SDIO_RDADDRESS_BITFIELDSIZE               32
#define SDIO_RDADDRESS_BITMASK                    0xffffffff
#define SDIO_RDADDRESS_INIT                       0x0

/*
 *  SDIO_WRADDREGL register defines
 ****************************************************************************************
 */
#define SDIO_WRADDREGL_OFFSETADDRESS   0x00000018  /* RW */
#define SDIO_WRADDREGL_BITOFFSET       0
#define SDIO_WRADDREGL_BITFIELDSIZE    32
#define SDIO_WRADDREGL_BITMASK         0xFFFFFFFF
#define SDIO_WRADDREGL_INIT            0x00000000
/*
 *  SDIO_ADDRESS bit field defines
 ****************************************************************************************
 */
#define SDIO_WRADDRESS_OFFSETADDRESS              SDIO_WRADDREGL_OFFSETADDRESS
#define SDIO_WRADDRESS_BITOFFSET                  0
#define SDIO_WRADDRESS_BITFIELDSIZE               32
#define SDIO_WRADDRESS_BITMASK                    0xffffffff
#define SDIO_WRADDRESS_INIT                       0x0

/*
 *  SDIO_PRGMREG register defines
 ****************************************************************************************
 */
#define SDIO_PRGMREG_OFFSETADDRESS     0x00000028  /* RW */
#define SDIO_PRGMREG_BITOFFSET         0
#define SDIO_PRGMREG_BITFIELDSIZE      32
#define SDIO_PRGMREG_BITMASK           0xFFFFFFFF
#define SDIO_PRGMREG_INIT              0x00000000
/*
 *  SDIO_FUNREADY bit field defines
 ****************************************************************************************
 */
#define SDIO_FUNREADY_OFFSETADDRESS             SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_FUNREADY_BITOFFSET                 0
#define SDIO_FUNREADY_BITFIELDSIZE              1
#define SDIO_FUNREADY_BITMASK                   0x00000001
#define SDIO_FUNREADY_INIT                      0x0
/*
 *  SDIO_FUN1RDDATAREADY bit field defines
 ****************************************************************************************
 */
#define SDIO_FUN1RDDATAREADY_OFFSETADDRESS      SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_FUN1RDDATAREADY_BITOFFSET          1
#define SDIO_FUN1RDDATAREADY_BITFIELDSIZE       1
#define SDIO_FUN1RDDATAREADY_BITMASK            0x00000002
#define SDIO_FUN1RDDATAREADY_INIT               0x0
/*
 *  SDIO_SCS1 bit field defines
 ****************************************************************************************
 */
#define SDIO_SCS1_OFFSETADDRESS                 SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_SCS1_BITOFFSET                     2
#define SDIO_SCS1_BITFIELDSIZE                  1
#define SDIO_SCS1_BITMASK                       0x00000004
#define SDIO_SCS1_INIT                          0x0
/*
 *  SDIO_SDC bit field defines
 ****************************************************************************************
 */
#define SDIO_SDC_OFFSETADDRESS                  SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_SDC_BITOFFSET                      3
#define SDIO_SDC_BITFIELDSIZE                   1
#define SDIO_SDC_BITMASK                        0x00000008
#define SDIO_SDC_INIT                           0x0
/*
 *  SDIO_SMB bit field defines
 ****************************************************************************************
 */
#define SDIO_SMB_OFFSETADDRESS                  SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_SMB_BITOFFSET                      4
#define SDIO_SMB_BITFIELDSIZE                   1
#define SDIO_SMB_BITMASK                        0x00000010
#define SDIO_SMB_INIT                           0x0
/*
 *  SDIO_SRW bit field defines
 ****************************************************************************************
 */
#define SDIO_SRW_OFFSETADDRESS                  SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_SRW_BITOFFSET                      5
#define SDIO_SRW_BITFIELDSIZE                   1
#define SDIO_SRW_BITMASK                        0x00000020
#define SDIO_SRW_INIT                           0x0
/*
 *  SDIO_SBS bit field defines
 ****************************************************************************************
 */
#define SDIO_SBS_OFFSETADDRESS                  SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_SBS_BITOFFSET                      6
#define SDIO_SBS_BITFIELDSIZE                   1
#define SDIO_SBS_BITMASK                        0x00000040
#define SDIO_SBS_INIT                           0x0
/*
 *  SDIO_S4MI bit field defines
 ****************************************************************************************
 */
#define SDIO_S4MI_OFFSETADDRESS                 SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_S4MI_BITOFFSET                     7
#define SDIO_S4MI_BITFIELDSIZE                  1
#define SDIO_S4MI_BITMASK                       0x00000080
#define SDIO_S4MI_INIT                          0x0
/*
 *  SDIO_LSC bit field defines
 ****************************************************************************************
 */
#define SDIO_LSC_OFFSETADDRESS                  SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_LSC_BITOFFSET                      8
#define SDIO_LSC_BITFIELDSIZE                   1
#define SDIO_LSC_BITMASK                        0x00000100
#define SDIO_LSC_INIT                           0x0
/*
 *  SDIO_BLS bit field defines
 ****************************************************************************************
 */
#define SDIO_BLS_OFFSETADDRESS                  SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_BLS_BITOFFSET                      9
#define SDIO_BLS_BITFIELDSIZE                   1
#define SDIO_BLS_BITMASK                        0x00000200
#define SDIO_BLS_INIT                           0x0
/*
 *  SDIO_CARDREADY bit field defines
 ****************************************************************************************
 */
#define SDIO_CARDREADY_OFFSETADDRESS            SDIO_PRGMREG_OFFSETADDRESS
#define SDIO_CARDREADY_BITOFFSET                10
#define SDIO_CARDREADY_BITFIELDSIZE             1
#define SDIO_CARDREADY_BITMASK                  0x00000400
#define SDIO_CARDREADY_INIT                     0x0

/*
 *  SDIO_INTRSTATUSREG register defines
 ****************************************************************************************
 */
#define SDIO_INTRSTATUSREG_OFFSETADDRESS 0x0000002C  /* RW */
#define SDIO_INTRSTATUSREG_BITOFFSET     0
#define SDIO_INTRSTATUSREG_BITFIELDSIZE  32
#define SDIO_INTRSTATUSREG_BITMASK       0xFFFFFFFF
#define SDIO_INTRSTATUSREG_INIT          0x00000000
/*
 *  SDIO_WRTOVER bit field defines
 ****************************************************************************************
 */
#define SDIO_INTRSTATUS_WRTOVER_OFFSETADDRESS              SDIO_INTRSTATUSREG_OFFSETADDRESS
#define SDIO_INTRSTATUS_WRTOVER_BITOFFSET                  0
#define SDIO_INTRSTATUS_WRTOVER_BITFIELDSIZE               1
#define SDIO_INTRSTATUS_WRTOVER_BITMASK                    0x00000001
#define SDIO_INTRSTATUS_WRTOVER_INIT                       0x0
/*
 *  SDIO_RDTOVER bit field defines
 ****************************************************************************************
 */
#define SDIO_INTRSTATUS_RDTOVER_OFFSETADDRESS              SDIO_INTRSTATUSREG_OFFSETADDRESS
#define SDIO_INTRSTATUS_RDTOVER_BITOFFSET                  1
#define SDIO_INTRSTATUS_RDTOVER_BITFIELDSIZE               1
#define SDIO_INTRSTATUS_RDTOVER_BITMASK                    0x00000002
#define SDIO_INTRSTATUS_RDTOVER_INIT                       0x0
/*
 *  SDIO_RDERROR bit field defines
 ****************************************************************************************
 */
#define SDIO_INTRSTATUS_RDERROR_OFFSETADDRESS              SDIO_INTRSTATUSREG_OFFSETADDRESS
#define SDIO_INTRSTATUS_RDERROR_BITOFFSET                  2
#define SDIO_INTRSTATUS_RDERROR_BITFIELDSIZE               1
#define SDIO_INTRSTATUS_RDERROR_BITMASK                    0x00000004
#define SDIO_INTRSTATUS_RDERROR_INIT                       0x0
/*
 *  SDIO_RSTSOFTINT bit field defines
 ****************************************************************************************
 */
#define SDIO_INTRSTATUS_RSTSOFTINT_OFFSETADDRESS           SDIO_INTRSTATUSREG_OFFSETADDRESS
#define SDIO_INTRSTATUS_RSTSOFTINT_BITOFFSET               3
#define SDIO_INTRSTATUS_RSTSOFTINT_BITFIELDSIZE            1
#define SDIO_INTRSTATUS_RSTSOFTINT_BITMASK                 0x00000008
#define SDIO_INTRSTATUS_RSTSOFTINT_INIT                    0x0
/*
 *  SDIO_RSTFUN1INt bit field defines
 ****************************************************************************************
 */
#define SDIO_INTRSTATUS_RSTFUN1INt_OFFSETADDRESS           SDIO_INTRSTATUSREG_OFFSETADDRESS
#define SDIO_INTRSTATUS_RSTFUN1INt_BITOFFSET               4
#define SDIO_INTRSTATUS_RSTFUN1INt_BITFIELDSIZE            1
#define SDIO_INTRSTATUS_RSTFUN1INt_BITMASK                 0x00000010
#define SDIO_INTRSTATUS_RSTFUN1INt_INIT                    0x0

/*
 *  SDIO_INTRENREG register defines
 ****************************************************************************************
 */
#define SDIO_INTRENREG_OFFSETADDRESS   0x00000030  /* RW */
#define SDIO_INTRENREG_BITOFFSET       0
#define SDIO_INTRENREG_BITFIELDSIZE    32
#define SDIO_INTRENREG_BITMASK         0xFFFFFFFF
#define SDIO_INTRENREG_INIT            0x00000000
/*
 *  SDIO_WRTOVER bit field defines
 ****************************************************************************************
 */
#define SDIO_WRTOVER_OFFSETADDRESS              SDIO_INTRENREG_OFFSETADDRESS
#define SDIO_WRTOVER_BITOFFSET                  0
#define SDIO_WRTOVER_BITFIELDSIZE               1
#define SDIO_WRTOVER_BITMASK                    0x00000001
#define SDIO_WRTOVER_INIT                       0x0
/*
 *  SDIO_RDTOVER bit field defines
 ****************************************************************************************
 */
#define SDIO_RDTOVER_OFFSETADDRESS              SDIO_INTRENREG_OFFSETADDRESS
#define SDIO_RDTOVER_BITOFFSET                  1
#define SDIO_RDTOVER_BITFIELDSIZE               1
#define SDIO_RDTOVER_BITMASK                    0x00000002
#define SDIO_RDTOVER_INIT                       0x0
/*
 *  SDIO_RDERROR bit field defines
 ****************************************************************************************
 */
#define SDIO_RDERROR_OFFSETADDRESS              SDIO_INTRENREG_OFFSETADDRESS
#define SDIO_RDERROR_BITOFFSET                  2
#define SDIO_RDERROR_BITFIELDSIZE               1
#define SDIO_RDERROR_BITMASK                    0x00000004
#define SDIO_RDERROR_INIT                       0x0
/*
 *  SDIO_RSTSOFTINT bit field defines
 ****************************************************************************************
 */
#define SDIO_RSTSOFTINT_OFFSETADDRESS           SDIO_INTRENREG_OFFSETADDRESS
#define SDIO_RSTSOFTINT_BITOFFSET               3
#define SDIO_RSTSOFTINT_BITFIELDSIZE            1
#define SDIO_RSTSOFTINT_BITMASK                 0x00000008
#define SDIO_RSTSOFTINT_INIT                    0x0
/*
 *  SDIO_RSTFUN1INt bit field defines
 ****************************************************************************************
 */
#define SDIO_RSTFUN1INt_OFFSETADDRESS           SDIO_INTRENREG_OFFSETADDRESS
#define SDIO_RSTFUN1INt_BITOFFSET               4
#define SDIO_RSTFUN1INt_BITFIELDSIZE            1
#define SDIO_RSTFUN1INt_BITMASK                 0x00000010
#define SDIO_RSTFUN1INt_INIT                    0x0

/*
 *  SDIO_AHBTXCOUNTREG register defines
 ****************************************************************************************
 */
#define SDIO_AHBTXCOUNTREG_OFFSETADDRESS 0x0000001C  /* RW */
#define SDIO_AHBTXCOUNTREG_BITOFFSET   0
#define SDIO_AHBTXCOUNTREG_BITFIELDSIZE 32
#define SDIO_AHBTXCOUNTREG_BITMASK     0xFFFFFFFF
#define SDIO_AHBTXCOUNTREG_INIT        0x00000000
/*
 *  SDIO_TXCOUNT bit field defines
 ****************************************************************************************
 */
#define SDIO_AHBTXCOUNT_OFFSETADDRESS              SDIO_AHBTXCOUNTREG_OFFSETADDRESS
#define SDIO_AHBTXCOUNT_BITOFFSET                  0
#define SDIO_AHBTXCOUNT_BITFIELDSIZE              21
#define SDIO_AHBTXCOUNT_BITMASK                    0x001fffff
#define SDIO_AHBTXCOUNT_INIT                       0x0

/*
 *  SDIO_SDIOTXCOUNTREG register defines
 ****************************************************************************************
 */
#define SDIO_SDIOTXCOUNTREG_OFFSETADDRESS 0x00000020  /* RW */
#define SDIO_SDIOTXCOUNTREG_BITOFFSET  0
#define SDIO_SDIOTXCOUNTREG_BITFIELDSIZE 32
#define SDIO_SDIOTXCOUNTREG_BITMASK    0xFFFFFFFF
#define SDIO_SDIOTXCOUNTREG_INIT       0x00000000
/*
 *  SDIO_TXCOUNT bit field defines
 ****************************************************************************************
 */
#define SDIO_SDTXCOUNT_OFFSETADDRESS              SDIO_SDIOTXCOUNTREG_OFFSETADDRESS
#define SDIO_SDTXCOUNT_BITOFFSET                  0
#define SDIO_SDTXCOUNT_BITFIELDSIZE               21
#define SDIO_SDTXCOUNT_BITMASK                    0x001fffff
#define SDIO_SDTXCOUNT_INIT                       0x0

/*
 *  SDIO_CIAREG register defines
 ****************************************************************************************
 */
#define SDIO_CIAREG_OFFSETADDRESS      0x00000024  /* RW */
#define SDIO_CIAREG_BITOFFSET          0
#define SDIO_CIAREG_BITFIELDSIZE       32
#define SDIO_CIAREG_BITMASK            0xFFFFFFFF
#define SDIO_CIAREG_INIT               0x00000000
/*
 *  SDIO_CCCRREV bit field defines
 ****************************************************************************************
 */
#define SDIO_CCCRREV_OFFSETADDRESS              SDIO_CIAREG_OFFSETADDRESS
#define SDIO_CCCRREV_BITOFFSET                  0
#define SDIO_CCCRREV_BITFIELDSIZE               4
#define SDIO_CCCRREV_BITMASK                    0x0000000f
#define SDIO_CCCRREV_INIT                       0x0
/*
 *  SDIO_SDIOREV bit field defines
 ****************************************************************************************
 */
#define SDIO_SDIOREV_OFFSETADDRESS              SDIO_CIAREG_OFFSETADDRESS
#define SDIO_SDIOREV_BITOFFSET                  4
#define SDIO_SDIOREV_BITFIELDSIZE               4
#define SDIO_SDIOREV_BITMASK                    0x000000f0
#define SDIO_SDIOREV_INIT                       0x0
/*
 *  SDIO_SDREV bit field defines
 ****************************************************************************************
 */
#define SDIO_SDREV_OFFSETADDRESS                SDIO_CIAREG_OFFSETADDRESS
#define SDIO_SDREV_BITOFFSET                    8
#define SDIO_SDREV_BITFIELDSIZE                 4
#define SDIO_SDREV_BITMASK                      0x00000f00
#define SDIO_SDREV_INIT                         0x0
/*
 *  SDIO_IODEVCODE1 bit field defines
 ****************************************************************************************
 */
#define SDIO_IODEVCODE1_OFFSETADDRESS           SDIO_CIAREG_OFFSETADDRESS
#define SDIO_IODEVCODE1_BITOFFSET              12
#define SDIO_IODEVCODE1_BITFIELDSIZE            4
#define SDIO_IODEVCODE1_BITMASK                 0x0000f000
#define SDIO_IODEVCODE1_INIT                    0x0
/*
 *  SDIO_CSASUPPORT1 bit field defines
 ****************************************************************************************
 */
#define SDIO_CSASUPPORT1_OFFSETADDRESS          SDIO_CIAREG_OFFSETADDRESS
#define SDIO_CSASUPPORT1_BITOFFSET             16
#define SDIO_CSASUPPORT1_BITFIELDSIZE           1
#define SDIO_CSASUPPORT1_BITMASK                0x00010000
#define SDIO_CSASUPPORT1_INIT                   0x0
/*
 *  SDIO_EIODEVCODE1 bit field defines
 ****************************************************************************************
 */
#define SDIO_EIODEVCODE1_OFFSETADDRESS          SDIO_CIAREG_OFFSETADDRESS
#define SDIO_EIODEVCODE1_BITOFFSET             17
#define SDIO_EIODEVCODE1_BITFIELDSIZE           8
#define SDIO_EIODEVCODE1_BITMASK                0x01fe0000
#define SDIO_EIODEVCODE1_INIT                   0x0
/*
 *  SDIO_SPS bit field defines
 ****************************************************************************************
 */
#define SDIO_SPS_OFFSETADDRESS                  SDIO_CIAREG_OFFSETADDRESS
#define SDIO_SPS_BITOFFSET                     25
#define SDIO_SPS_BITFIELDSIZE                   1
#define SDIO_SPS_BITMASK                        0x02000000
#define SDIO_SPS_INIT                           0x0
/*
 *  SDIO_SHS bit field defines
 ****************************************************************************************
 */
#define SDIO_SHS_OFFSETADDRESS                  SDIO_CIAREG_OFFSETADDRESS
#define SDIO_SHS_BITOFFSET                     26
#define SDIO_SHS_BITFIELDSIZE                   1
#define SDIO_SHS_BITMASK                        0x04000000
#define SDIO_SHS_INIT                           0x0
/*
 *  SDIO_SMPC bit field defines
 ****************************************************************************************
 */
#define SDIO_SMPC_OFFSETADDRESS                 SDIO_CIAREG_OFFSETADDRESS
#define SDIO_SMPC_BITOFFSET                    27
#define SDIO_SMPC_BITFIELDSIZE                  1
#define SDIO_SMPC_BITMASK                       0x08000000
#define SDIO_SMPC_INIT                          0x0
/*
 *  SDIO_RFU bit field defines
 ****************************************************************************************
 */
#define SDIO_RFU_OFFSETADDRESS                  SDIO_CIAREG_OFFSETADDRESS
#define SDIO_RFU_BITOFFSET                     28
#define SDIO_RFU_BITFIELDSIZE                   4
#define SDIO_RFU_BITMASK                        0xf0000000
#define SDIO_RFU_INIT                           0x0

/*
 *  SDIO_OCRREG register defines
 ****************************************************************************************
 */
#define SDIO_OCRREG_OFFSETADDRESS      0x00000034  /* RW */
#define SDIO_OCRREG_BITOFFSET          0
#define SDIO_OCRREG_BITFIELDSIZE       32
#define SDIO_OCRREG_BITMASK            0xFFFFFFFF
#define SDIO_OCRREG_INIT               0x00000000
/*
 *  SDIO_OCR bit field defines
 ****************************************************************************************
 */
#define SDIO_OCR_OFFSETADDRESS                  SDIO_OCRREG_OFFSETADDRESS
#define SDIO_OCR_BITOFFSET                      0
#define SDIO_OCR_BITFIELDSIZE                  24
#define SDIO_OCR_BITMASK                        0x00ffffff
#define SDIO_OCR_INIT                           0x0

/*
 *  SDIO_CLKWAKEREG register defines
 ****************************************************************************************
 */
#define SDIO_CLKWAKEREG_OFFSETADDRESS  0x00000038  /* RW */
#define SDIO_CLKWAKEREG_BITOFFSET      0
#define SDIO_CLKWAKEREG_BITFIELDSIZE   32
#define SDIO_CLKWAKEREG_BITMASK        0xFFFFFFFF
#define SDIO_CLKWAKEREG_INIT           0x00000000
/*
 *  SDIO_AUTOCLKEN bit field defines
 ****************************************************************************************
 */
#define SDIO_AUTOCLKEN_OFFSETADDRESS            SDIO_CLKWAKEREG_OFFSETADDRESS
#define SDIO_AUTOCLKEN_BITOFFSET                0
#define SDIO_AUTOCLKEN_BITFIELDSIZE             1
#define SDIO_AUTOCLKEN_BITMASK                  0x00000001
#define SDIO_AUTOCLKEN_INIT                     0x0
/*
 *  SDIO_MANUALOCLKEN bit field defines
 ****************************************************************************************
 */
#define SDIO_MANUALOCLKEN_OFFSETADDRESS         SDIO_CLKWAKEREG_OFFSETADDRESS
#define SDIO_MANUALOCLKEN_BITOFFSET             1
#define SDIO_MANUALOCLKEN_BITFIELDSIZE          1
#define SDIO_MANUALOCLKEN_BITMASK               0x00000002
#define SDIO_MANUALOCLKEN_INIT                  0x0

/*
 *  SDIO_AHBBSIZE register defines
 ****************************************************************************************
 */
#define SDIO_AHBBSIZE_OFFSETADDRESS    0x0000003c  /* RW */
#define SDIO_AHBBSIZE_BITOFFSET        0
#define SDIO_AHBBSIZE_BITFIELDSIZE     32
#define SDIO_AHBBSIZE_BITMASK          0xFFFFFFFF
#define SDIO_AHBBSIZE_INIT             0x00000000
/*
 *  SDIO_SIZE bit field defines
 ****************************************************************************************
 */
#define SDIO_SIZE_OFFSETADDRESS                 SDIO_AHBBSIZE_OFFSETADDRESS
#define SDIO_SIZE_BITOFFSET                     0
#define SDIO_SIZE_BITFIELDSIZE                  3
#define SDIO_SIZE_BITMASK                       0x00000007
#define SDIO_SIZE_INIT                          0x0

/*
 *  SDIO_AHBSOFTRSTREG register defines
 ****************************************************************************************
 */
#define SDIO_AHBSOFTRSTREG_OFFSETADDRESS 0x00000040  /* RW */
#define SDIO_AHBSOFTRSTREG_BITOFFSET   0
#define SDIO_AHBSOFTRSTREG_BITFIELDSIZE 32
#define SDIO_AHBSOFTRSTREG_BITMASK     0xFFFFFFFF
#define SDIO_AHBSOFTRSTREG_INIT        0x00000000
/*
 *  SDIO_VALID bit field defines
 ****************************************************************************************
 */
#define SDIO_VALID_OFFSETADDRESS                SDIO_AHBSOFTRSTREG_OFFSETADDRESS
#define SDIO_VALID_BITOFFSET                    0
#define SDIO_VALID_BITFIELDSIZE                 1
#define SDIO_VALID_BITMASK                      0x00000001
#define SDIO_VALID_INIT                         0x0
#endif
