/*
 ****************************************************************************************
 * reg_sdio_mac.h
 *
 * Copyright (C) NewLogic 2003-2005
 *
 * Project: LPX Software
 *
 * Description:
 *    File generated by reg_build.py from ..\HWdriver\header\xml\reg_sdio.xml
 *
 *
 * Attention : This file must be used with precaution. Somes of its macros can be
 *             non-pertinent. But the original XML file doesn't allow to be pertinent.
 *             So don't include this file as header file. Copy/Paste is preferable.
 *
 ****************************************************************************************
 */

#ifndef _REG_SDIO_MAC_H
#define _REG_SDIO_MAC_H

/***************************************************
 *
 *             SDIO
 *
 ***************************************************/


/*
 *  SDIO_DATAPORT register macros
 ****************************************************************************************
 */
#define SDIO_DATAPORT_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_DATAPORT))
#define SDIO_DATAPORT_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_DATAPORT, (value))
#define SDIO_DATAPORT_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_DATAPORT, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_DATAPORT) | (value))
#define SDIO_DATAPORT_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_DATAPORT, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_DATAPORT) & (~(value)))

/*
 *  SDIO_DATA bit field macros
 ****************************************************************************************
 */
#define SDIO_DATA_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_DATA)
#define SDIO_DATA_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_DATA, (value))


/*
 *  SDIO_IIR register macros
 ****************************************************************************************
 */
#define SDIO_IIR_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_IIR))
#define SDIO_IIR_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_IIR, (value))
#define SDIO_IIR_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_IIR, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_IIR) | (value))
#define SDIO_IIR_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_IIR, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_IIR) & (~(value)))

/*
 *  SDIO_DATARDY bit field macros
 ****************************************************************************************
 */
#define SDIO_DATARDY_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_DATARDY)
#define SDIO_DATARDY_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_DATARDY, 1)
#define SDIO_DATARDY_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_DATARDY, 0)

/*
 *  SDIO_ERROR bit field macros
 ****************************************************************************************
 */
#define SDIO_ERROR_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_ERROR)
#define SDIO_ERROR_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_ERROR, 1)
#define SDIO_ERROR_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_ERROR, 0)


/*
 *  SDIO_CISFUN0ADDREG register macros
 ****************************************************************************************
 */
#define SDIO_CISFUN0ADDREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CISFUN0ADDREG))
#define SDIO_CISFUN0ADDREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CISFUN0ADDREG, (value))
#define SDIO_CISFUN0ADDREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CISFUN0ADDREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CISFUN0ADDREG) | (value))
#define SDIO_CISFUN0ADDREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CISFUN0ADDREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CISFUN0ADDREG) & (~(value)))

/*
 *  SDIO_ADDRESS bit field macros
 ****************************************************************************************
 */
#define SDIO_CISFUN0ADDRESS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_CISFUN0ADDREG)
#define SDIO_CISFUN0ADDRESS_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_CISFUN0ADDREG, (value))


/*
 *  SDIO_CISFUN1ADDREG register macros
 ****************************************************************************************
 */
#define SDIO_CISFUN1ADDREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CISFUN1ADDREG))

/*
 *  SDIO_ADDRESS bit field macros
 ****************************************************************************************
 */
#define SDIO_CISFUN1ADDRESS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_CISFUN1ADDREG)
#define SDIO_CISFUN1ADDRESS_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_CISFUN1ADDREG, (value))


/*
 *  SDIO_CSAADDREG register macros
 ****************************************************************************************
 */
#define SDIO_CSAADDREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CSAADDREG))
#define SDIO_CSAADDREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CSAADDREG, (value))
#define SDIO_CSAADDREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CSAADDREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CSAADDREG) | (value))
#define SDIO_CSAADDREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CSAADDREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CSAADDREG) & (~(value)))

/*
 *  SDIO_ADDRESS bit field macros
 ****************************************************************************************
 */
#define SDIO_CSAADDRESS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_CSAADDREG)
#define SDIO_CSAADDRESS_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_CSAADDREG, (value))


/*
 *  SDIO_RDADDREG register macros
 ****************************************************************************************
 */
#define SDIO_RDADDREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_RDADDREG))
#define SDIO_RDADDREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_RDADDREG, (value))
#define SDIO_RDADDREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_RDADDREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_RDADDREG) | (value))
#define SDIO_RDADDREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_RDADDREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_RDADDREG) & (~(value)))

/*
 *  SDIO_ADDRESS bit field macros
 ****************************************************************************************
 */
#define SDIO_RDADDRESS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_ADDRESS)
#define SDIO_RDADDRESS_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_ADDRESS, (value))


/*
 *  SDIO_WRADDREGL register macros
 ****************************************************************************************
 */
#define SDIO_WRADDREGL_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_WRADDREGL))
#define SDIO_WRADDREGL_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_WRADDREGL, (value))
#define SDIO_WRADDREGL_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_WRADDREGL, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_WRADDREGL) | (value))
#define SDIO_WRADDREGL_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_WRADDREGL, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_WRADDREGL) & (~(value)))

/*
 *  SDIO_ADDRESS bit field macros
 ****************************************************************************************
 */
#define SDIO_WRADDRESS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_ADDRESS)
#define SDIO_WRADDRESS_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_ADDRESS, (value))


/*
 *  SDIO_PRGMREG register macros
 ****************************************************************************************
 */
#define SDIO_PRGMREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_PRGMREG))
#define SDIO_PRGMREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_PRGMREG, (value))
#define SDIO_PRGMREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_PRGMREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_PRGMREG) | (value))
#define SDIO_PRGMREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_PRGMREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_PRGMREG) & (~(value)))

/*
 *  SDIO_FUNREADY bit field macros
 ****************************************************************************************
 */
#define SDIO_FUNREADY_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_FUNREADY)
#define SDIO_FUNREADY_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_FUNREADY, 1)
#define SDIO_FUNREADY_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_FUNREADY, 0)

/*
 *  SDIO_FUN1RDDATAREADY bit field macros
 ****************************************************************************************
 */
#define SDIO_FUN1RDDATAREADY_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_FUN1RDDATAREADY)
#define SDIO_FUN1RDDATAREADY_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_FUN1RDDATAREADY, 1)
#define SDIO_FUN1RDDATAREADY_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_FUN1RDDATAREADY, 0)

/*
 *  SDIO_SCS1 bit field macros
 ****************************************************************************************
 */
#define SDIO_SCS1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SCS1)
#define SDIO_SCS1_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SCS1, 1)
#define SDIO_SCS1_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SCS1, 0)

/*
 *  SDIO_SDC bit field macros
 ****************************************************************************************
 */
#define SDIO_SDC_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SDC)
#define SDIO_SDC_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SDC, 1)
#define SDIO_SDC_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SDC, 0)

/*
 *  SDIO_SMB bit field macros
 ****************************************************************************************
 */
#define SDIO_SMB_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SMB)
#define SDIO_SMB_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SMB, 1)
#define SDIO_SMB_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SMB, 0)

/*
 *  SDIO_SRW bit field macros
 ****************************************************************************************
 */
#define SDIO_SRW_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SRW)
#define SDIO_SRW_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SRW, 1)
#define SDIO_SRW_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SRW, 0)

/*
 *  SDIO_SBS bit field macros
 ****************************************************************************************
 */
#define SDIO_SBS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SBS)
#define SDIO_SBS_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SBS, 1)
#define SDIO_SBS_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SBS, 0)

/*
 *  SDIO_S4MI bit field macros
 ****************************************************************************************
 */
#define SDIO_S4MI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_S4MI)
#define SDIO_S4MI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_S4MI, 1)
#define SDIO_S4MI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_S4MI, 0)

/*
 *  SDIO_LSC bit field macros
 ****************************************************************************************
 */
#define SDIO_LSC_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_LSC)
#define SDIO_LSC_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_LSC, 1)
#define SDIO_LSC_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_LSC, 0)

/*
 *  SDIO_BLS bit field macros
 ****************************************************************************************
 */
#define SDIO_BLS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_BLS)
#define SDIO_BLS_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_BLS, 1)
#define SDIO_BLS_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_BLS, 0)

/*
 *  SDIO_CARDREADY bit field macros
 ****************************************************************************************
 */
#define SDIO_CARDREADY_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_CARDREADY)
#define SDIO_CARDREADY_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_CARDREADY, 1)
#define SDIO_CARDREADY_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_CARDREADY, 0)


/*
 *  SDIO_INTRSTATUSREG register macros
 ****************************************************************************************
 */
#define SDIO_INTRSTATUSREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRSTATUSREG))
#define SDIO_INTRSTATUSREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRSTATUSREG, (value))
#define SDIO_INTRSTATUSREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRSTATUSREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRSTATUSREG) | (value))
#define SDIO_INTRSTATUSREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRSTATUSREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRSTATUSREG) & (~(value)))

/*
 *  SDIO_WRTOVER bit field macros
 ****************************************************************************************
 */
#define SDIO_WRTOVER_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_WRTOVER)
#define SDIO_WRTOVER_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_WRTOVER, 1)
#define SDIO_WRTOVER_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_WRTOVER, 0)

/*
 *  SDIO_RDTOVER bit field macros
 ****************************************************************************************
 */
#define SDIO_RDTOVER_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_RDTOVER)
#define SDIO_RDTOVER_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RDTOVER, 1)
#define SDIO_RDTOVER_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RDTOVER, 0)

/*
 *  SDIO_RDERROR bit field macros
 ****************************************************************************************
 */
#define SDIO_RDERROR_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_RDERROR)
#define SDIO_RDERROR_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RDERROR, 1)
#define SDIO_RDERROR_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RDERROR, 0)

/*
 *  SDIO_RSTSOFTINT bit field macros
 ****************************************************************************************
 */
#define SDIO_RSTSOFTINT_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_RSTSOFTINT)
#define SDIO_RSTSOFTINT_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RSTSOFTINT, 1)
#define SDIO_RSTSOFTINT_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RSTSOFTINT, 0)

/*
 *  SDIO_RSTFUN1INt bit field macros
 ****************************************************************************************
 */
#define SDIO_RSTFUN1INt_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_RSTFUN1INt)
#define SDIO_RSTFUN1INt_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RSTFUN1INt, 1)
#define SDIO_RSTFUN1INt_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RSTFUN1INt, 0)


/*
 *  SDIO_INTRENREG register macros
 ****************************************************************************************
 */
#define SDIO_INTRENREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRENREG))
#define SDIO_INTRENREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRENREG, (value))
#define SDIO_INTRENREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRENREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRENREG) | (value))
#define SDIO_INTRENREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRENREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_INTRENREG) & (~(value)))

/*
 *  SDIO_WRTOVER bit field macros
 ****************************************************************************************
 */
#define SDIO_WRTOVER_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_WRTOVER)
#define SDIO_WRTOVER_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_WRTOVER, 1)
#define SDIO_WRTOVER_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_WRTOVER, 0)

/*
 *  SDIO_RDTOVER bit field macros
 ****************************************************************************************
 */
#define SDIO_RDTOVER_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_RDTOVER)
#define SDIO_RDTOVER_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RDTOVER, 1)
#define SDIO_RDTOVER_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RDTOVER, 0)

/*
 *  SDIO_RDERROR bit field macros
 ****************************************************************************************
 */
#define SDIO_RDERROR_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_RDERROR)
#define SDIO_RDERROR_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RDERROR, 1)
#define SDIO_RDERROR_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RDERROR, 0)

/*
 *  SDIO_RSTSOFTINT bit field macros
 ****************************************************************************************
 */
#define SDIO_RSTSOFTINT_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_RSTSOFTINT)
#define SDIO_RSTSOFTINT_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RSTSOFTINT, 1)
#define SDIO_RSTSOFTINT_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RSTSOFTINT, 0)

/*
 *  SDIO_RSTFUN1INt bit field macros
 ****************************************************************************************
 */
#define SDIO_RSTFUN1INt_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_RSTFUN1INt)
#define SDIO_RSTFUN1INt_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RSTFUN1INt, 1)
#define SDIO_RSTFUN1INt_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_RSTFUN1INt, 0)


/*
 *  SDIO_AHBTXCOUNTREG register macros
 ****************************************************************************************
 */
#define SDIO_AHBTXCOUNTREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBTXCOUNTREG))
#define SDIO_AHBTXCOUNTREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBTXCOUNTREG, (value))
#define SDIO_AHBTXCOUNTREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBTXCOUNTREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBTXCOUNTREG) | (value))
#define SDIO_AHBTXCOUNTREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBTXCOUNTREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBTXCOUNTREG) & (~(value)))

/*
 *  SDIO_TXCOUNT bit field macros
 ****************************************************************************************
 */
#define SDIO_AHBTXCOUNT_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_AHBTXCOUNT)
#define SDIO_AHBTXCOUNT_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_AHBTXCOUNT, (value))


/*
 *  SDIO_SDIOTXCOUNTREG register macros
 ****************************************************************************************
 */
#define SDIO_SDIOTXCOUNTREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_SDIOTXCOUNTREG))
#define SDIO_SDIOTXCOUNTREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_SDIOTXCOUNTREG, (value))
#define SDIO_SDIOTXCOUNTREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_SDIOTXCOUNTREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_SDIOTXCOUNTREG) | (value))
#define SDIO_SDIOTXCOUNTREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_SDIOTXCOUNTREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_SDIOTXCOUNTREG) & (~(value)))

/*
 *  SDIO_TXCOUNT bit field macros
 ****************************************************************************************
 */
#define SDIO_SDTXCOUNT_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SDTXCOUNT)
#define SDIO_SDTXCOUNT_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_SDTXCOUNT, (value))


/*
 *  SDIO_CIAREG register macros
 ****************************************************************************************
 */
#define SDIO_CIAREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CIAREG))
#define SDIO_CIAREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CIAREG, (value))
#define SDIO_CIAREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CIAREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CIAREG) | (value))
#define SDIO_CIAREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CIAREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CIAREG) & (~(value)))

/*
 *  SDIO_CCCRREV bit field macros
 ****************************************************************************************
 */
#define SDIO_CCCRREV_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_CCCRREV)
#define SDIO_CCCRREV_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_CCCRREV, (value))

/*
 *  SDIO_SDIOREV bit field macros
 ****************************************************************************************
 */
#define SDIO_SDIOREV_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SDIOREV)
#define SDIO_SDIOREV_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_SDIOREV, (value))

/*
 *  SDIO_SDREV bit field macros
 ****************************************************************************************
 */
#define SDIO_SDREV_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SDREV)
#define SDIO_SDREV_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_SDREV, (value))

/*
 *  SDIO_IODEVCODE1 bit field macros
 ****************************************************************************************
 */
#define SDIO_IODEVCODE1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_IODEVCODE1)
#define SDIO_IODEVCODE1_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_IODEVCODE1, (value))

/*
 *  SDIO_CSASUPPORT1 bit field macros
 ****************************************************************************************
 */
#define SDIO_CSASUPPORT1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_CSASUPPORT1)
#define SDIO_CSASUPPORT1_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_CSASUPPORT1, 1)
#define SDIO_CSASUPPORT1_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_CSASUPPORT1, 0)

/*
 *  SDIO_EIODEVCODE1 bit field macros
 ****************************************************************************************
 */
#define SDIO_EIODEVCODE1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_EIODEVCODE1)
#define SDIO_EIODEVCODE1_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_EIODEVCODE1, (value))

/*
 *  SDIO_SPS bit field macros
 ****************************************************************************************
 */
#define SDIO_SPS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SPS)
#define SDIO_SPS_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SPS, 1)
#define SDIO_SPS_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SPS, 0)

/*
 *  SDIO_SHS bit field macros
 ****************************************************************************************
 */
#define SDIO_SHS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SHS)
#define SDIO_SHS_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SHS, 1)
#define SDIO_SHS_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SHS, 0)

/*
 *  SDIO_SMPC bit field macros
 ****************************************************************************************
 */
#define SDIO_SMPC_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SMPC)
#define SDIO_SMPC_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SMPC, 1)
#define SDIO_SMPC_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_SMPC, 0)

/*
 *  SDIO_RFU bit field macros
 ****************************************************************************************
 */
#define SDIO_RFU_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_RFU)
#define SDIO_RFU_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_RFU, (value))


/*
 *  SDIO_OCRREG register macros
 ****************************************************************************************
 */
#define SDIO_OCRREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_OCRREG))
#define SDIO_OCRREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_OCRREG, (value))
#define SDIO_OCRREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_OCRREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_OCRREG) | (value))
#define SDIO_OCRREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_OCRREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_OCRREG) & (~(value)))

/*
 *  SDIO_OCR bit field macros
 ****************************************************************************************
 */
#define SDIO_OCR_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_OCR)
#define SDIO_OCR_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_OCR, (value))


/*
 *  SDIO_CLKWAKEREG register macros
 ****************************************************************************************
 */
#define SDIO_CLKWAKEREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CLKWAKEREG))
#define SDIO_CLKWAKEREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CLKWAKEREG, (value))
#define SDIO_CLKWAKEREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CLKWAKEREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CLKWAKEREG) | (value))
#define SDIO_CLKWAKEREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CLKWAKEREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_CLKWAKEREG) & (~(value)))

/*
 *  SDIO_AUTOCLKEN bit field macros
 ****************************************************************************************
 */
#define SDIO_AUTOCLKEN_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_AUTOCLKEN)
#define SDIO_AUTOCLKEN_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_AUTOCLKEN, 1)
#define SDIO_AUTOCLKEN_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_AUTOCLKEN, 0)

/*
 *  SDIO_MANUALOCLKEN bit field macros
 ****************************************************************************************
 */
#define SDIO_MANUALOCLKEN_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_MANUALOCLKEN)
#define SDIO_MANUALOCLKEN_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_MANUALOCLKEN, 1)
#define SDIO_MANUALOCLKEN_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_MANUALOCLKEN, 0)


/*
 *  SDIO_AHBBSIZE register macros
 ****************************************************************************************
 */
#define SDIO_AHBBSIZE_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBBSIZE))
#define SDIO_AHBBSIZE_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBBSIZE, (value))
#define SDIO_AHBBSIZE_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBBSIZE, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBBSIZE) | (value))
#define SDIO_AHBBSIZE_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBBSIZE, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBBSIZE) & (~(value)))

/*
 *  SDIO_SIZE bit field macros
 ****************************************************************************************
 */
#define SDIO_SIZE_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_SIZE)
#define SDIO_SIZE_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, SDIO_SIZE, (value))


/*
 *  SDIO_AHBSOFTRSTREG register macros
 ****************************************************************************************
 */
#define SDIO_AHBSOFTRSTREG_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBSOFTRSTREG))
#define SDIO_AHBSOFTRSTREG_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBSOFTRSTREG, (value))
#define SDIO_AHBSOFTRSTREG_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBSOFTRSTREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBSOFTRSTREG) | (value))
#define SDIO_AHBSOFTRSTREG_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBSOFTRSTREG, GET_WORD_EXCLUSIVE_BITFIELD(addr, SDIO_AHBSOFTRSTREG) & (~(value)))

/*
 *  SDIO_VALID bit field macros
 ****************************************************************************************
 */
#define SDIO_VALID_GET(addr) \
        GET_WORD_BITFIELD_N(addr, SDIO_VALID)
#define SDIO_VALID_SET(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_VALID, 1)
#define SDIO_VALID_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, SDIO_VALID, 0)

#endif
