/*
 ****************************************************************************************
 * reg_i2c_mac.h
 *
 * Copyright (C) NewLogic 2003-2005
 *
 * Project: LPX Software
 *
 * Description:
 *    File generated by reg_build.py from ..\HWdriver\header\xml\reg_i2c.xml
 *
 *
 * Attention : This file must be used with precaution. Somes of its macros can be
 *             non-pertinent. But the original XML file doesn't allow to be pertinent.
 *             So don't include this file as header file. Copy/Paste is preferable.
 *
 ****************************************************************************************
 */

#ifndef _REG_I2C_MAC_H
#define _REG_I2C_MAC_H

/***************************************************
 *
 *             I2C
 *
 ***************************************************/


/*
 *  I2C_I2CSLAD0 register macros
 ****************************************************************************************
 */
#define I2C_I2CSLAD0_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD0))
#define I2C_I2CSLAD0_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD0, (value))
#define I2C_I2CSLAD0_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD0, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD0) | (value))
#define I2C_I2CSLAD0_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD0, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD0) & (~(value)))

/*
 *  I2C_SLAD0 bit field macros
 ****************************************************************************************
 */
#define I2C_SLAD0_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_SLAD0)
#define I2C_SLAD0_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, I2C_SLAD0, (value))


/*
 *  I2C_I2CSLAD1 register macros
 ****************************************************************************************
 */
#define I2C_I2CSLAD1_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD1))
#define I2C_I2CSLAD1_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD1, (value))
#define I2C_I2CSLAD1_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD1, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD1) | (value))
#define I2C_I2CSLAD1_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD1, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CSLAD1) & (~(value)))

/*
 *  I2C_SLAD1 bit field macros
 ****************************************************************************************
 */
#define I2C_SLAD1_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_SLAD1)
#define I2C_SLAD1_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, I2C_SLAD1, (value))

/*
 *  I2C_ADMOD bit field macros
 ****************************************************************************************
 */
#define I2C_ADMOD_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_ADMOD)
#define I2C_ADMOD_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_ADMOD, 1)
#define I2C_ADMOD_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_ADMOD, 0)

/*
 *  I2C_MNS bit field macros
 ****************************************************************************************
 */
#define I2C_MNS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_MNS)
#define I2C_MNS_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_MNS, 1)
#define I2C_MNS_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_MNS, 0)

/*
 *  I2C_HSE bit field macros
 ****************************************************************************************
 */
#define I2C_HSE_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_HSE)
#define I2C_HSE_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_HSE, 1)
#define I2C_HSE_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_HSE, 0)


/*
 *  I2C_I2CIER register macros
 ****************************************************************************************
 */
#define I2C_I2CIER_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CIER))
#define I2C_I2CIER_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CIER, (value))
#define I2C_I2CIER_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CIER, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CIER) | (value))
#define I2C_I2CIER_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CIER, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CIER) & (~(value)))

/*
 *  I2C_EFEI bit field macros
 ****************************************************************************************
 */
#define I2C_EFEI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_EFEI)
#define I2C_EFEI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_EFEI, 1)
#define I2C_EFEI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_EFEI, 0)

/*
 *  I2C_EBI bit field macros
 ****************************************************************************************
 */
#define I2C_EBI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_EBI)
#define I2C_EBI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_EBI, 1)
#define I2C_EBI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_EBI, 0)

/*
 *  I2C_EFFI bit field macros
 ****************************************************************************************
 */
#define I2C_EFFI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_EFFI)
#define I2C_EFFI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_EFFI, 1)
#define I2C_EFFI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_EFFI, 0)

/*
 *  I2C_EOCI bit field macros
 ****************************************************************************************
 */
#define I2C_EOCI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_EOCI)
#define I2C_EOCI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_EOCI, 1)
#define I2C_EOCI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_EOCI, 0)

/*
 *  I2C_ENAEI bit field macros
 ****************************************************************************************
 */
#define I2C_ENAEI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_ENAEI)
#define I2C_ENAEI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_ENAEI, 1)
#define I2C_ENAEI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_ENAEI, 0)

/*
 *  I2C_AFI bit field macros
 ****************************************************************************************
 */
#define I2C_EAFI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_EAFI)
#define I2C_EAFI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_EAFI, 1)
#define I2C_EAFI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_EAFI, 0)


/*
 *  I2C_I2CISR register macros
 ****************************************************************************************
 */
#define I2C_I2CISR_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CISR))
#define I2C_I2CISR_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CISR, (value))
#define I2C_I2CISR_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CISR, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CISR) | (value))
#define I2C_I2CISR_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CISR, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CISR) & (~(value)))

/*
 *  I2C_FEI bit field macros
 ****************************************************************************************
 */
#define I2C_FEI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_FEI)
#define I2C_FEI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_FEI, 1)
#define I2C_FEI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_FEI, 1)

/*
 *  I2C_BI bit field macros
 ****************************************************************************************
 */
#define I2C_BI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_BI)
#define I2C_BI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_BI, 1)
#define I2C_BI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_BI, 1)

/*
 *  I2C_FFI bit field macros
 ****************************************************************************************
 */
#define I2C_FFI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_FFI)
#define I2C_FFI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_FFI, 1)
#define I2C_FFI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_FFI, 1)

/*
 *  I2C_OCI bit field macros
 ****************************************************************************************
 */
#define I2C_OCI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_OCI)
#define I2C_OCI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_OCI, 1)
#define I2C_OCI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_OCI, 1)

/*
 *  I2C_NAEI bit field macros
 ****************************************************************************************
 */
#define I2C_NAEI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_NAEI)
#define I2C_NAEI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_NAEI, 1)
#define I2C_NAEI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_NAEI, 1)

/*
 *  I2C_AFI bit field macros
 ****************************************************************************************
 */
#define I2C_AFI_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_AFI)
#define I2C_AFI_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_AFI, 1)
#define I2C_AFI_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_AFI, 1)


/*
 *  I2C_I2CAPBADDRLSB register macros
 ****************************************************************************************
 */
#define I2C_I2CAPBADDRLSB_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRLSB))
#define I2C_I2CAPBADDRLSB_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRLSB, (value))
#define I2C_I2CAPBADDRLSB_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRLSB, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRLSB) | (value))
#define I2C_I2CAPBADDRLSB_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRLSB, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRLSB) & (~(value)))

/*
 *  I2C_I2CAPBADDRMSB register macros
 ****************************************************************************************
 */
#define I2C_I2CAPBADDRMSB_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRMSB))
#define I2C_I2CAPBADDRMSB_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRMSB, (value))
#define I2C_I2CAPBADDRMSB_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRMSB, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRMSB) | (value))
#define I2C_I2CAPBADDRMSB_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRMSB, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CAPBADDRMSB) & (~(value)))

/*
 *  I2C_I2CDACNTLSB register macros
 ****************************************************************************************
 */
#define I2C_I2CDACNTLSB_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTLSB))
#define I2C_I2CDACNTLSB_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTLSB, (value))
#define I2C_I2CDACNTLSB_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTLSB, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTLSB) | (value))
#define I2C_I2CDACNTLSB_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTLSB, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTLSB) & (~(value)))


/*
 *  I2C_DACNT bit field macros
 ****************************************************************************************
 */
#define I2C_DACNT_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_DACNT)
#define I2C_DACNT_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, I2C_DACNT, (value))

/*
 *  I2C_I2CDATA register macros
 ****************************************************************************************
 */
#define I2C_I2CDATA_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDATA))
#define I2C_I2CDATA_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDATA, (value))
#define I2C_I2CDATA_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDATA, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDATA) | (value))
#define I2C_I2CDATA_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDATA, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDATA) & (~(value)))



/*
 *  I2C_DATA bit field macros
 ****************************************************************************************
 */
#define I2C_DATA_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_DATA)
#define I2C_DATA_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, I2C_DATA, (value))


/*
 *  I2C_I2CCR register macros
 ****************************************************************************************
 */
#define I2C_I2CCR_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CCR))
#define I2C_I2CCR_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CCR, (value))
#define I2C_I2CCR_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CCR, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CCR) | (value))
#define I2C_I2CCR_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CCR, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CCR) & (~(value)))

/*
 *  I2C_RWOP bit field macros
 ****************************************************************************************
 */
#define I2C_RWOP_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_RWOP)
#define I2C_RWOP_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_RWOP, 1)
#define I2C_RWOP_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_RWOP, 0)

/*
 *  I2C_AOP bit field macros
 ****************************************************************************************
 */
#define I2C_AOP_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_AOP)
#define I2C_AOP_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_AOP, 1)
#define I2C_AOP_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_AOP, 0)

/*
 *  I2C_BCO bit field macros
 ****************************************************************************************
 */
#define I2C_BCO_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_BCO)
#define I2C_BCO_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_BCO, 1)
#define I2C_BCO_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_BCO, 0)

/*
 *  I2C_RCAS bit field macros
 ****************************************************************************************
 */
#define I2C_RCAS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_RCAS)
#define I2C_RCAS_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_RCAS, 1)
#define I2C_RCAS_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_RCAS, 0)

/*
 *  I2C_MAS bit field macros
 ****************************************************************************************
 */
#define I2C_MAS_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_MAS)
#define I2C_MAS_SET(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_MAS, 1)
#define I2C_MAS_CLEAR(addr) \
        SET_WORD_BITFIELD_N(addr, I2C_MAS, 0)


/*
 *  I2C_I2CADDRLSB register macros
 ****************************************************************************************
 */
#define I2C_I2CADDRLSB_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRLSB))
#define I2C_I2CADDRLSB_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRLSB, (value))
#define I2C_I2CADDRLSB_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRLSB, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRLSB) | (value))
#define I2C_I2CADDRLSB_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRLSB, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRLSB) & (~(value)))

/*
 *  I2C_SADDRLSB bit field macros
 ****************************************************************************************
 */
#define I2C_SADDRLSB_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_SADDRLSB)
#define I2C_SADDRLSB_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, I2C_SADDRLSB, (value))


/*
 *  I2C_I2CADDRMSB register macros
 ****************************************************************************************
 */
#define I2C_I2CADDRMSB_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRMSB))
#define I2C_I2CADDRMSB_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRMSB, (value))
#define I2C_I2CADDRMSB_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRMSB, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRMSB) | (value))
#define I2C_I2CADDRMSB_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRMSB, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CADDRMSB) & (~(value)))

/*
 *  I2C_SADDRMSB bit field macros
 ****************************************************************************************
 */
#define I2C_SADDRMSB_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_SADDRMSB)
#define I2C_SADDRMSB_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, I2C_SADDRMSB, (value))


/*
 *  I2C_I2CDACNTR register macros
 ****************************************************************************************
 */
#define I2C_I2CDACNTR_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTR))
#define I2C_I2CDACNTR_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTR, (value))
#define I2C_I2CDACNTR_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTR, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTR) | (value))
#define I2C_I2CDACNTR_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTR, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CDACNTR) & (~(value)))

/*
 *  I2C_SDACNT bit field macros
 ****************************************************************************************
 */
#define I2C_SDACNT_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_SDACNT)
#define I2C_SDACNT_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, I2C_SDACNT, (value))


/*
 *  I2C_I2CMCR register macros
 ****************************************************************************************
 */
#define I2C_I2CMCR_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CMCR))
#define I2C_I2CMCR_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CMCR, (value))
#define I2C_I2CMCR_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CMCR, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CMCR) | (value))
#define I2C_I2CMCR_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CMCR, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CMCR) & (~(value)))

/*
 *  I2C_MCODE bit field macros
 ****************************************************************************************
 */
#define I2C_MCODE_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_MCODE)
#define I2C_MCODE_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, I2C_MCODE, (value))


/*
 *  I2C_I2CHCCR register macros
 ****************************************************************************************
 */
#define I2C_I2CHCCR_GET(addr) \
        (GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CHCCR))
#define I2C_I2CHCCR_SET(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CHCCR, (value))
#define I2C_I2CHCCR_SETBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CHCCR, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CHCCR) | (value))
#define I2C_I2CHCCR_CLEARBIT(addr, value) \
        SET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CHCCR, GET_WORD_EXCLUSIVE_BITFIELD(addr, I2C_I2CHCCR) & (~(value)))

/*
 *  I2C_CCOUNT bit field macros
 ****************************************************************************************
 */
#define I2C_CCOUNT_GET(addr) \
        GET_WORD_BITFIELD_N(addr, I2C_CCOUNT)
#define I2C_CCOUNT_SET(addr, value) \
        SET_WORD_BITFIELD_N(addr, I2C_CCOUNT, (value))

#endif
