/*
 ****************************************************************************************
 * reg_gs2000tmr.h
 *
 * Copyright (C) NewLogic 2003-2005
 *
 * Project: LPX Software
 *
 * Description:
 *    File generated by reg_build.py from ..\HWdriver\header\xml\GS2000TMR.xml
 *
 *
 * Attention : This file must be used with precaution. Somes of its macros can be
 *             non-pertinent. But the original XML file doesn't allow to be pertinent.
 *             So don't include this file as header file. Copy/Paste is preferable.
 *
 ****************************************************************************************
 */

#ifndef _REG_GS2000TMR_H
#define _REG_GS2000TMR_H

/***************************************************
 *
 *             GS2000TMR
 *
 ***************************************************/


/*
 *  GS2000TMR instance offsets
 ****************************************************************************************
 */
#define GS2000TMR 0x40130000

/*
 *  GS2000TMR_PCOUNT_LSB register defines
 ****************************************************************************************
 */
#define GS2000TMR_PCOUNT_LSB_OFFSETADDRESS 0x00000000  /* R */
#define GS2000TMR_PCOUNT_LSB_BITOFFSET 0
#define GS2000TMR_PCOUNT_LSB_BITFIELDSIZE 32
#define GS2000TMR_PCOUNT_LSB_BITMASK   0xFFFFFFFF
#define GS2000TMR_PCOUNT_LSB_INIT      0x00000000
/*
 *  GS2000TMR_COUNT_LSB bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_COUNT_LSB_OFFSETADDRESS       GS2000TMR_PCOUNT_LSB_OFFSETADDRESS
#define GS2000TMR_COUNT_LSB_BITOFFSET           0
#define GS2000TMR_COUNT_LSB_BITFIELDSIZE       32
#define GS2000TMR_COUNT_LSB_BITMASK             0xffffffff
#define GS2000TMR_COUNT_LSB_INIT                0x0

/*
 *  GS2000TMR_PCOUNT_MSB register defines
 ****************************************************************************************
 */
#define GS2000TMR_PCOUNT_MSB_OFFSETADDRESS 0x00000004  /* R */
#define GS2000TMR_PCOUNT_MSB_BITOFFSET 0
#define GS2000TMR_PCOUNT_MSB_BITFIELDSIZE 32
#define GS2000TMR_PCOUNT_MSB_BITMASK   0xFFFFFFFF
#define GS2000TMR_PCOUNT_MSB_INIT      0x00000000
/*
 *  GS2000TMR_COUNT_MSB bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_COUNT_MSB_OFFSETADDRESS       GS2000TMR_PCOUNT_MSB_OFFSETADDRESS
#define GS2000TMR_COUNT_MSB_BITOFFSET           0
#define GS2000TMR_COUNT_MSB_BITFIELDSIZE       32
#define GS2000TMR_COUNT_MSB_BITMASK             0xffffffff
#define GS2000TMR_COUNT_MSB_INIT                0x0

/*
 *  GS2000TMR_VALID register defines
 ****************************************************************************************
 */
#define GS2000TMR_VALID_OFFSETADDRESS  0x00000008  /* RW */
#define GS2000TMR_VALID_BITOFFSET      0
#define GS2000TMR_VALID_BITFIELDSIZE   32
#define GS2000TMR_VALID_BITMASK        0xFFFFFFFF
#define GS2000TMR_VALID_INIT           0x00000000
/*
 *  GS2000TMR_COUNT_VALID bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_COUNT_VALID_OFFSETADDRESS     GS2000TMR_VALID_OFFSETADDRESS
#define GS2000TMR_COUNT_VALID_BITOFFSET         0
#define GS2000TMR_COUNT_VALID_BITFIELDSIZE      1
#define GS2000TMR_COUNT_VALID_BITMASK           0x00000001
#define GS2000TMR_COUNT_VALID_INIT              0x0

/*
 *  GS2000TMR_COMPARE_LSB register defines
 ****************************************************************************************
 */
#define GS2000TMR_COMPARE_LSB_OFFSETADDRESS 0x0000000c  /* RW */
#define GS2000TMR_COMPARE_LSB_BITOFFSET 0
#define GS2000TMR_COMPARE_LSB_BITFIELDSIZE 32
#define GS2000TMR_COMPARE_LSB_BITMASK  0xFFFFFFFF
#define GS2000TMR_COMPARE_LSB_INIT     0x00000000
/*
 *  GS2000TMR_COMP_LSB bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_COMP_LSB_OFFSETADDRESS        GS2000TMR_COMPARE_LSB_OFFSETADDRESS
#define GS2000TMR_COMP_LSB_BITOFFSET            0
#define GS2000TMR_COMP_LSB_BITFIELDSIZE        32
#define GS2000TMR_COMP_LSB_BITMASK              0xffffffff
#define GS2000TMR_COMP_LSB_INIT                 0x0

/*
 *  GS2000TMR_COMPARE_MSB register defines
 ****************************************************************************************
 */
#define GS2000TMR_COMPARE_MSB_OFFSETADDRESS 0x00000010  /* RW */
#define GS2000TMR_COMPARE_MSB_BITOFFSET 0
#define GS2000TMR_COMPARE_MSB_BITFIELDSIZE 32
#define GS2000TMR_COMPARE_MSB_BITMASK  0xFFFFFFFF
#define GS2000TMR_COMPARE_MSB_INIT     0x00000000
/*
 *  GS2000TMR_COMP_MSB bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_COMP_MSB_OFFSETADDRESS        GS2000TMR_COMPARE_MSB_OFFSETADDRESS
#define GS2000TMR_COMP_MSB_BITOFFSET            0
#define GS2000TMR_COMP_MSB_BITFIELDSIZE        32
#define GS2000TMR_COMP_MSB_BITMASK              0xffffffff
#define GS2000TMR_COMP_MSB_INIT                 0x0

/*
 *  GS2000TMR_COMPARE_IRQ_STATUS register defines
 ****************************************************************************************
 */
#define GS2000TMR_COMPARE_IRQ_STATUS_OFFSETADDRESS 0x00000014  /* R */
#define GS2000TMR_COMPARE_IRQ_STATUS_BITOFFSET 0
#define GS2000TMR_COMPARE_IRQ_STATUS_BITFIELDSIZE 32
#define GS2000TMR_COMPARE_IRQ_STATUS_BITMASK 0xFFFFFFFF
#define GS2000TMR_COMPARE_IRQ_STATUS_INIT 0x00000000
/*
 *  GS2000TMR_COMP_IRQ_STATUS bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_COMP_IRQ_STATUS_OFFSETADDRESS GS2000TMR_COMPARE_IRQ_STATUS_OFFSETADDRESS
#define GS2000TMR_COMP_IRQ_STATUS_BITOFFSET     0
#define GS2000TMR_COMP_IRQ_STATUS_BITFIELDSIZE  1
#define GS2000TMR_COMP_IRQ_STATUS_BITMASK       0x00000001
#define GS2000TMR_COMP_IRQ_STATUS_INIT          0x0

/*
 *  GS2000TMR_COMPARE_IRQ_MASK register defines
 ****************************************************************************************
 */
#define GS2000TMR_COMPARE_IRQ_MASK_OFFSETADDRESS 0x00000018  /* RW */
#define GS2000TMR_COMPARE_IRQ_MASK_BITOFFSET 0
#define GS2000TMR_COMPARE_IRQ_MASK_BITFIELDSIZE 32
#define GS2000TMR_COMPARE_IRQ_MASK_BITMASK 0xFFFFFFFF
#define GS2000TMR_COMPARE_IRQ_MASK_INIT 0x00000000
/*
 *  GS2000TMR_COMP_IRQ_MASK bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_COMP_IRQ_MASK_OFFSETADDRESS   GS2000TMR_COMPARE_IRQ_MASK_OFFSETADDRESS
#define GS2000TMR_COMP_IRQ_MASK_BITOFFSET       0
#define GS2000TMR_COMP_IRQ_MASK_BITFIELDSIZE    1
#define GS2000TMR_COMP_IRQ_MASK_BITMASK         0x00000001
#define GS2000TMR_COMP_IRQ_MASK_INIT            0x0

/*
 *  GS2000TMR_COMPARE_IRQ_CLEAR register defines
 ****************************************************************************************
 */
#define GS2000TMR_COMPARE_IRQ_CLEAR_OFFSETADDRESS 0x0000001c  /* RW */
#define GS2000TMR_COMPARE_IRQ_CLEAR_BITOFFSET 0
#define GS2000TMR_COMPARE_IRQ_CLEAR_BITFIELDSIZE 32
#define GS2000TMR_COMPARE_IRQ_CLEAR_BITMASK 0xFFFFFFFF
#define GS2000TMR_COMPARE_IRQ_CLEAR_INIT 0x00000000
/*
 *  GS2000TMR_COMP_IRQ_CLEAR bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_COMP_IRQ_CLEAR_OFFSETADDRESS  GS2000TMR_COMPARE_IRQ_CLEAR_OFFSETADDRESS
#define GS2000TMR_COMP_IRQ_CLEAR_BITOFFSET      0
#define GS2000TMR_COMP_IRQ_CLEAR_BITFIELDSIZE   1
#define GS2000TMR_COMP_IRQ_CLEAR_BITMASK        0x00000001
#define GS2000TMR_COMP_IRQ_CLEAR_INIT           0x0

/*
 *  GS2000TMR_COMPARE_IRQ_SET register defines
 ****************************************************************************************
 */
#define GS2000TMR_COMPARE_IRQ_SET_OFFSETADDRESS 0x00000020  /* RW */
#define GS2000TMR_COMPARE_IRQ_SET_BITOFFSET 0
#define GS2000TMR_COMPARE_IRQ_SET_BITFIELDSIZE 32
#define GS2000TMR_COMPARE_IRQ_SET_BITMASK 0xFFFFFFFF
#define GS2000TMR_COMPARE_IRQ_SET_INIT 0x00000000
/*
 *  GS2000TMR_COMP_IRQ_SET bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_COMP_IRQ_SET_OFFSETADDRESS    GS2000TMR_COMPARE_IRQ_SET_OFFSETADDRESS
#define GS2000TMR_COMP_IRQ_SET_BITOFFSET        0
#define GS2000TMR_COMP_IRQ_SET_BITFIELDSIZE     1
#define GS2000TMR_COMP_IRQ_SET_BITMASK          0x00000001
#define GS2000TMR_COMP_IRQ_SET_INIT             0x0

/*
 *  GS2000TMR_ALARM_IRQ_STATUS register defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_IRQ_STATUS_OFFSETADDRESS 0x00000080  /* R */
#define GS2000TMR_ALARM_IRQ_STATUS_BITOFFSET 0
#define GS2000TMR_ALARM_IRQ_STATUS_BITFIELDSIZE 32
#define GS2000TMR_ALARM_IRQ_STATUS_BITMASK 0xFFFFFFFF
#define GS2000TMR_ALARM_IRQ_STATUS_INIT 0x00000000
/*
 *  GS2000TMR_ALARM_0_IRQ_STATUS bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_0_IRQ_STATUS_OFFSETADDRESS GS2000TMR_ALARM_IRQ_STATUS_OFFSETADDRESS
#define GS2000TMR_ALARM_0_IRQ_STATUS_BITOFFSET  0
#define GS2000TMR_ALARM_0_IRQ_STATUS_BITFIELDSIZE  1
#define GS2000TMR_ALARM_0_IRQ_STATUS_BITMASK    0x00000001
#define GS2000TMR_ALARM_0_IRQ_STATUS_INIT       0x0
/*
 *  GS2000TMR_ALARM_1_IRQ_STATUS bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_1_IRQ_STATUS_OFFSETADDRESS GS2000TMR_ALARM_IRQ_STATUS_OFFSETADDRESS
#define GS2000TMR_ALARM_1_IRQ_STATUS_BITOFFSET  1
#define GS2000TMR_ALARM_1_IRQ_STATUS_BITFIELDSIZE  1
#define GS2000TMR_ALARM_1_IRQ_STATUS_BITMASK    0x00000002
#define GS2000TMR_ALARM_1_IRQ_STATUS_INIT       0x0
/*
 *  GS2000TMR_ALARM_2_IRQ_STATUS bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_2_IRQ_STATUS_OFFSETADDRESS GS2000TMR_ALARM_IRQ_STATUS_OFFSETADDRESS
#define GS2000TMR_ALARM_2_IRQ_STATUS_BITOFFSET  2
#define GS2000TMR_ALARM_2_IRQ_STATUS_BITFIELDSIZE  1
#define GS2000TMR_ALARM_2_IRQ_STATUS_BITMASK    0x00000004
#define GS2000TMR_ALARM_2_IRQ_STATUS_INIT       0x0
/*
 *  GS2000TMR_ALARM_3_IRQ_STATUS bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_3_IRQ_STATUS_OFFSETADDRESS GS2000TMR_ALARM_IRQ_STATUS_OFFSETADDRESS
#define GS2000TMR_ALARM_3_IRQ_STATUS_BITOFFSET  3
#define GS2000TMR_ALARM_3_IRQ_STATUS_BITFIELDSIZE  1
#define GS2000TMR_ALARM_3_IRQ_STATUS_BITMASK    0x00000008
#define GS2000TMR_ALARM_3_IRQ_STATUS_INIT       0x0
/*
 *  GS2000TMR_ALARM_4_IRQ_STATUS bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_4_IRQ_STATUS_OFFSETADDRESS GS2000TMR_ALARM_IRQ_STATUS_OFFSETADDRESS
#define GS2000TMR_ALARM_4_IRQ_STATUS_BITOFFSET  4
#define GS2000TMR_ALARM_4_IRQ_STATUS_BITFIELDSIZE  1
#define GS2000TMR_ALARM_4_IRQ_STATUS_BITMASK    0x00000010
#define GS2000TMR_ALARM_4_IRQ_STATUS_INIT       0x0

/*
 *  GS2000TMR_ALARM_IRQ_MASK register defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_IRQ_MASK_OFFSETADDRESS 0x00000084  /* RW */
#define GS2000TMR_ALARM_IRQ_MASK_BITOFFSET 0
#define GS2000TMR_ALARM_IRQ_MASK_BITFIELDSIZE 32
#define GS2000TMR_ALARM_IRQ_MASK_BITMASK 0xFFFFFFFF
#define GS2000TMR_ALARM_IRQ_MASK_INIT  0x00000000
/*
 *  GS2000TMR_ALARM_0_IRQ_MASK bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_0_IRQ_MASK_OFFSETADDRESS GS2000TMR_ALARM_IRQ_MASK_OFFSETADDRESS
#define GS2000TMR_ALARM_0_IRQ_MASK_BITOFFSET    0
#define GS2000TMR_ALARM_0_IRQ_MASK_BITFIELDSIZE  1
#define GS2000TMR_ALARM_0_IRQ_MASK_BITMASK      0x00000001
#define GS2000TMR_ALARM_0_IRQ_MASK_INIT         0x0
/*
 *  GS2000TMR_ALARM_1_IRQ_MASK bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_1_IRQ_MASK_OFFSETADDRESS GS2000TMR_ALARM_IRQ_MASK_OFFSETADDRESS
#define GS2000TMR_ALARM_1_IRQ_MASK_BITOFFSET    1
#define GS2000TMR_ALARM_1_IRQ_MASK_BITFIELDSIZE  1
#define GS2000TMR_ALARM_1_IRQ_MASK_BITMASK      0x00000002
#define GS2000TMR_ALARM_1_IRQ_MASK_INIT         0x0
/*
 *  GS2000TMR_ALARM_2_IRQ_MASK bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_2_IRQ_MASK_OFFSETADDRESS GS2000TMR_ALARM_IRQ_MASK_OFFSETADDRESS
#define GS2000TMR_ALARM_2_IRQ_MASK_BITOFFSET    2
#define GS2000TMR_ALARM_2_IRQ_MASK_BITFIELDSIZE  1
#define GS2000TMR_ALARM_2_IRQ_MASK_BITMASK      0x00000004
#define GS2000TMR_ALARM_2_IRQ_MASK_INIT         0x0
/*
 *  GS2000TMR_ALARM_3_IRQ_MASK bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_3_IRQ_MASK_OFFSETADDRESS GS2000TMR_ALARM_IRQ_MASK_OFFSETADDRESS
#define GS2000TMR_ALARM_3_IRQ_MASK_BITOFFSET    3
#define GS2000TMR_ALARM_3_IRQ_MASK_BITFIELDSIZE  1
#define GS2000TMR_ALARM_3_IRQ_MASK_BITMASK      0x00000008
#define GS2000TMR_ALARM_3_IRQ_MASK_INIT         0x0
/*
 *  GS2000TMR_ALARM_4_IRQ_MASK bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_4_IRQ_MASK_OFFSETADDRESS GS2000TMR_ALARM_IRQ_MASK_OFFSETADDRESS
#define GS2000TMR_ALARM_4_IRQ_MASK_BITOFFSET    4
#define GS2000TMR_ALARM_4_IRQ_MASK_BITFIELDSIZE  1
#define GS2000TMR_ALARM_4_IRQ_MASK_BITMASK      0x00000010
#define GS2000TMR_ALARM_4_IRQ_MASK_INIT         0x0

/*
 *  GS2000TMR_ALARM_IRQ_CLEAR register defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_IRQ_CLEAR_OFFSETADDRESS 0x00000088  /* RW */
#define GS2000TMR_ALARM_IRQ_CLEAR_BITOFFSET 0
#define GS2000TMR_ALARM_IRQ_CLEAR_BITFIELDSIZE 32
#define GS2000TMR_ALARM_IRQ_CLEAR_BITMASK 0xFFFFFFFF
#define GS2000TMR_ALARM_IRQ_CLEAR_INIT 0x00000000
/*
 *  GS2000TMR_ALARM_0_IRQ_CLEAR bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_0_IRQ_CLEAR_OFFSETADDRESS GS2000TMR_ALARM_IRQ_CLEAR_OFFSETADDRESS
#define GS2000TMR_ALARM_0_IRQ_CLEAR_BITOFFSET   0
#define GS2000TMR_ALARM_0_IRQ_CLEAR_BITFIELDSIZE  1
#define GS2000TMR_ALARM_0_IRQ_CLEAR_BITMASK     0x00000001
#define GS2000TMR_ALARM_0_IRQ_CLEAR_INIT        0x0
/*
 *  GS2000TMR_ALARM_1_IRQ_CLEAR bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_1_IRQ_CLEAR_OFFSETADDRESS GS2000TMR_ALARM_IRQ_CLEAR_OFFSETADDRESS
#define GS2000TMR_ALARM_1_IRQ_CLEAR_BITOFFSET   1
#define GS2000TMR_ALARM_1_IRQ_CLEAR_BITFIELDSIZE  1
#define GS2000TMR_ALARM_1_IRQ_CLEAR_BITMASK     0x00000002
#define GS2000TMR_ALARM_1_IRQ_CLEAR_INIT        0x0
/*
 *  GS2000TMR_ALARM_2_IRQ_CLEAR bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_2_IRQ_CLEAR_OFFSETADDRESS GS2000TMR_ALARM_IRQ_CLEAR_OFFSETADDRESS
#define GS2000TMR_ALARM_2_IRQ_CLEAR_BITOFFSET   2
#define GS2000TMR_ALARM_2_IRQ_CLEAR_BITFIELDSIZE  1
#define GS2000TMR_ALARM_2_IRQ_CLEAR_BITMASK     0x00000004
#define GS2000TMR_ALARM_2_IRQ_CLEAR_INIT        0x0
/*
 *  GS2000TMR_ALARM_3_IRQ_CLEAR bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_3_IRQ_CLEAR_OFFSETADDRESS GS2000TMR_ALARM_IRQ_CLEAR_OFFSETADDRESS
#define GS2000TMR_ALARM_3_IRQ_CLEAR_BITOFFSET   3
#define GS2000TMR_ALARM_3_IRQ_CLEAR_BITFIELDSIZE  1
#define GS2000TMR_ALARM_3_IRQ_CLEAR_BITMASK     0x00000008
#define GS2000TMR_ALARM_3_IRQ_CLEAR_INIT        0x0
/*
 *  GS2000TMR_ALARM_4_IRQ_CLEAR bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_4_IRQ_CLEAR_OFFSETADDRESS GS2000TMR_ALARM_IRQ_CLEAR_OFFSETADDRESS
#define GS2000TMR_ALARM_4_IRQ_CLEAR_BITOFFSET   4
#define GS2000TMR_ALARM_4_IRQ_CLEAR_BITFIELDSIZE  1
#define GS2000TMR_ALARM_4_IRQ_CLEAR_BITMASK     0x00000010
#define GS2000TMR_ALARM_4_IRQ_CLEAR_INIT        0x0

/*
 *  GS2000TMR_ALARM_IRQ_SET register defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_IRQ_SET_OFFSETADDRESS 0x0000008c  /* RW */
#define GS2000TMR_ALARM_IRQ_SET_BITOFFSET 0
#define GS2000TMR_ALARM_IRQ_SET_BITFIELDSIZE 32
#define GS2000TMR_ALARM_IRQ_SET_BITMASK 0xFFFFFFFF
#define GS2000TMR_ALARM_IRQ_SET_INIT   0x00000000
/*
 *  GS2000TMR_ALARM_0_IRQ_SET bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_0_IRQ_SET_OFFSETADDRESS GS2000TMR_ALARM_IRQ_SET_OFFSETADDRESS
#define GS2000TMR_ALARM_0_IRQ_SET_BITOFFSET     0
#define GS2000TMR_ALARM_0_IRQ_SET_BITFIELDSIZE  1
#define GS2000TMR_ALARM_0_IRQ_SET_BITMASK       0x00000001
#define GS2000TMR_ALARM_0_IRQ_SET_INIT          0x0
/*
 *  GS2000TMR_ALARM_1_IRQ_SET bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_1_IRQ_SET_OFFSETADDRESS GS2000TMR_ALARM_IRQ_SET_OFFSETADDRESS
#define GS2000TMR_ALARM_1_IRQ_SET_BITOFFSET     1
#define GS2000TMR_ALARM_1_IRQ_SET_BITFIELDSIZE  1
#define GS2000TMR_ALARM_1_IRQ_SET_BITMASK       0x00000002
#define GS2000TMR_ALARM_1_IRQ_SET_INIT          0x0
/*
 *  GS2000TMR_ALARM_2_IRQ_SET bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_2_IRQ_SET_OFFSETADDRESS GS2000TMR_ALARM_IRQ_SET_OFFSETADDRESS
#define GS2000TMR_ALARM_2_IRQ_SET_BITOFFSET     2
#define GS2000TMR_ALARM_2_IRQ_SET_BITFIELDSIZE  1
#define GS2000TMR_ALARM_2_IRQ_SET_BITMASK       0x00000004
#define GS2000TMR_ALARM_2_IRQ_SET_INIT          0x0
/*
 *  GS2000TMR_ALARM_3_IRQ_SET bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_3_IRQ_SET_OFFSETADDRESS GS2000TMR_ALARM_IRQ_SET_OFFSETADDRESS
#define GS2000TMR_ALARM_3_IRQ_SET_BITOFFSET     3
#define GS2000TMR_ALARM_3_IRQ_SET_BITFIELDSIZE  1
#define GS2000TMR_ALARM_3_IRQ_SET_BITMASK       0x00000008
#define GS2000TMR_ALARM_3_IRQ_SET_INIT          0x0
/*
 *  GS2000TMR_ALARM_4_IRQ_SET bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_4_IRQ_SET_OFFSETADDRESS GS2000TMR_ALARM_IRQ_SET_OFFSETADDRESS
#define GS2000TMR_ALARM_4_IRQ_SET_BITOFFSET     4
#define GS2000TMR_ALARM_4_IRQ_SET_BITFIELDSIZE  1
#define GS2000TMR_ALARM_4_IRQ_SET_BITMASK       0x00000010
#define GS2000TMR_ALARM_4_IRQ_SET_INIT          0x0

/*
 *  GS2000TMR_ALARM_TS0 register defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_TS0_OFFSETADDRESS 0x000000a0  /* RW */
#define GS2000TMR_ALARM_TS0_BITOFFSET  0
#define GS2000TMR_ALARM_TS0_BITFIELDSIZE 32
#define GS2000TMR_ALARM_TS0_BITMASK    0xFFFFFFFF
#define GS2000TMR_ALARM_TS0_INIT       0x00000000
/*
 *  GS2000TMR_ALARM_TS_0 bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_TS_0_OFFSETADDRESS      GS2000TMR_ALARM_TS0_OFFSETADDRESS
#define GS2000TMR_ALARM_TS_0_BITOFFSET          0
#define GS2000TMR_ALARM_TS_0_BITFIELDSIZE      10
#define GS2000TMR_ALARM_TS_0_BITMASK            0x000003ff
#define GS2000TMR_ALARM_TS_0_INIT               0x0

/*
 *  GS2000TMR_ALARM_TS1 register defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_TS1_OFFSETADDRESS 0x000000a4  /* RW */
#define GS2000TMR_ALARM_TS1_BITOFFSET  0
#define GS2000TMR_ALARM_TS1_BITFIELDSIZE 32
#define GS2000TMR_ALARM_TS1_BITMASK    0xFFFFFFFF
#define GS2000TMR_ALARM_TS1_INIT       0x00000000
/*
 *  GS2000TMR_ALARM_TS_1 bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_TS_1_OFFSETADDRESS      GS2000TMR_ALARM_TS1_OFFSETADDRESS
#define GS2000TMR_ALARM_TS_1_BITOFFSET          0
#define GS2000TMR_ALARM_TS_1_BITFIELDSIZE      10
#define GS2000TMR_ALARM_TS_1_BITMASK            0x000003ff
#define GS2000TMR_ALARM_TS_1_INIT               0x0

/*
 *  GS2000TMR_ALARM_TS2 register defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_TS2_OFFSETADDRESS 0x000000a8  /* RW */
#define GS2000TMR_ALARM_TS2_BITOFFSET  0
#define GS2000TMR_ALARM_TS2_BITFIELDSIZE 32
#define GS2000TMR_ALARM_TS2_BITMASK    0xFFFFFFFF
#define GS2000TMR_ALARM_TS2_INIT       0x00000000
/*
 *  GS2000TMR_ALARM_TS_2 bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_TS_2_OFFSETADDRESS      GS2000TMR_ALARM_TS2_OFFSETADDRESS
#define GS2000TMR_ALARM_TS_2_BITOFFSET          0
#define GS2000TMR_ALARM_TS_2_BITFIELDSIZE      10
#define GS2000TMR_ALARM_TS_2_BITMASK            0x000003ff
#define GS2000TMR_ALARM_TS_2_INIT               0x0

/*
 *  GS2000TMR_ALARM_TS3 register defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_TS3_OFFSETADDRESS 0x000000ac  /* RW */
#define GS2000TMR_ALARM_TS3_BITOFFSET  0
#define GS2000TMR_ALARM_TS3_BITFIELDSIZE 32
#define GS2000TMR_ALARM_TS3_BITMASK    0xFFFFFFFF
#define GS2000TMR_ALARM_TS3_INIT       0x00000000
/*
 *  GS2000TMR_ALARM_TS_3 bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_TS_3_OFFSETADDRESS      GS2000TMR_ALARM_TS3_OFFSETADDRESS
#define GS2000TMR_ALARM_TS_3_BITOFFSET          0
#define GS2000TMR_ALARM_TS_3_BITFIELDSIZE      10
#define GS2000TMR_ALARM_TS_3_BITMASK            0x000003ff
#define GS2000TMR_ALARM_TS_3_INIT               0x0

/*
 *  GS2000TMR_ALARM_TS4 register defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_TS4_OFFSETADDRESS 0x000000b0  /* RW */
#define GS2000TMR_ALARM_TS4_BITOFFSET  0
#define GS2000TMR_ALARM_TS4_BITFIELDSIZE 32
#define GS2000TMR_ALARM_TS4_BITMASK    0xFFFFFFFF
#define GS2000TMR_ALARM_TS4_INIT       0x00000000
/*
 *  GS2000TMR_ALARM_TS_4 bit field defines
 ****************************************************************************************
 */
#define GS2000TMR_ALARM_TS_4_OFFSETADDRESS      GS2000TMR_ALARM_TS4_OFFSETADDRESS
#define GS2000TMR_ALARM_TS_4_BITOFFSET          0
#define GS2000TMR_ALARM_TS_4_BITFIELDSIZE      10
#define GS2000TMR_ALARM_TS_4_BITMASK            0x000003ff
#define GS2000TMR_ALARM_TS_4_INIT               0x0
#endif
