
#ifndef _GSN_IOMUX_H_
#define _GSN_IOMUX_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "gsn_includes.h"
#include "core/reg/gsn_reg_iomux_spec.h"
#include "core/reg/gsn_reg_iomux_op.h"

#define GSN_IO_MUX_BASE_ADDR 0x40160000

INLINE VOID
GsnIoMux_Sel(UINT32 gpioNum, UINT32 muxVal)
{
	*(UINT32 *)(GSN_IO_MUX_BASE_ADDR + (gpioNum << 2)) = muxVal;
}

INLINE VOID
GsnIoMux_PullDownEnable(UINT32 gpioNum)
{
    UINT32 oldVal;
    INT32 intr;
   
    intr = GsnOsal_IntrDisable();
    if (gpioNum < 32)
    {
        oldVal = *((UINT32 *)(GSN_IO_MUX_BASE_ADDR + 0x200));
        *((UINT32 *)(GSN_IO_MUX_BASE_ADDR + 0x200)) = (~(1 << gpioNum)) & oldVal;
    }
    else
    {
        oldVal = *((UINT32 *)(GSN_IO_MUX_BASE_ADDR + 0x204));
        *((UINT32 *)(GSN_IO_MUX_BASE_ADDR + 0x204)) = (~(1 << (gpioNum- 32))) & oldVal;
    }
    GsnOsal_IntrEnable(intr);
}

INLINE VOID
GsnIoMux_PullDownDisable(UINT32 gpioNum)
{
    UINT32 oldVal;
    INT32 intr;
   
    intr = GsnOsal_IntrDisable();
    if (gpioNum < 32)
    {
        oldVal = *((UINT32 *)(GSN_IO_MUX_BASE_ADDR + 0x200));
        *((UINT32 *)(GSN_IO_MUX_BASE_ADDR + 0x200)) = (1 << gpioNum) | oldVal;
    }
    else
    {
        oldVal = *((UINT32 *)(GSN_IO_MUX_BASE_ADDR + 0x204));
        *((UINT32 *)(GSN_IO_MUX_BASE_ADDR + 0x204)) = (1 << (gpioNum - 32)) | oldVal;
    }
    GsnOsal_IntrEnable(intr);
}

typedef enum GSN_IOMUX_GPIO_0
{
	GSN_IOMUX_GPIO_0_AGPIO_0,
	GSN_IOMUX_GPIO_0_WGPIO_0,
	GSN_IOMUX_GPIO_0_DEBUG_21,
	GSN_IOMUX_GPIO_0_AUART0_RXD,
	GSN_IOMUX_GPIO_0_WUART_RXD,
	GSN_IOMUX_GPIO_0_APWM_2,
	GSN_IOMUX_GPIO_0_CM3_TRACEDATA_2,
	GSN_IOMUX_GPIO_0_ASSP1_DIN	
	
}GSN_IOMUX_GPIO_0;

typedef enum GSN_IOMUX_GPIO_1
{
	GSN_IOMUX_GPIO_1_AGPIO_1,
	GSN_IOMUX_GPIO_1_WGPIO_1,
	GSN_IOMUX_GPIO_1_DEBUG_20,
	GSN_IOMUX_GPIO_1_AUART0_TXD,
	GSN_IOMUX_GPIO_1_WUART_TXD,
	GSN_IOMUX_GPIO_1_APWM_1,
	GSN_IOMUX_GPIO_1_CM3_TRACEDATA_0,
	GSN_IOMUX_GPIO_1_ASSP1_DOUT

}GSN_IOMUX_GPIO_1;


typedef enum GSN_IOMUX_GPIO_2
{

	GSN_IOMUX_GPIO_2_AGPIO_2,
	GSN_IOMUX_GPIO_2_WGPIO_2,
	GSN_IOMUX_GPIO_2_DEBUG_19,
	GSN_IOMUX_GPIO_2_AUART1_TXD,
	GSN_IOMUX_GPIO_2_WUART_TXD,
	GSN_IOMUX_GPIO_2_AI2S_LRCLK,
	GSN_IOMUX_GPIO_2_ASSP1_CS_15, 	
	GSN_IOMUX_GPIO_2_WSSP_BI_CS 

}GSN_IOMUX_GPIO_2;

typedef enum GSN_IOMUX_GPIO_3
{
	GSN_IOMUX_GPIO_3_AGPIO_3,
	GSN_IOMUX_GPIO_3_WGPIO_3,
	GSN_IOMUX_GPIO_3_DEBUG_18,
	GSN_IOMUX_GPIO_3__AUART1_RXD,
	GSN_IOMUX_GPIO_3_WUART_RXD,
	GSN_IOMUX_GPIO_3_AI2S_BITCLK,
	GSN_IOMUX_GPIO_3_ASSP1_CS_14,
	GSN_IOMUX_GPIO_3_WSSP_DIN
	
}GSN_IOMUX_GPIO_3;



typedef enum GSN_IOMUX_GPIO_4
{
	GSN_IOMUX_GPIO_4_AGPIO_4,
	GSN_IOMUX_GPIO_4_WGPIO_4,
	GSN_IOMUX_GPIO_4_DEBUG_9,
	GSN_IOMUX_GPIO_4_ASSP1_BI_CS,
	GSN_IOMUX_GPIO_4_WSSP_BI_CS,
	GSN_IOMUX_GPIO_4_ASSP0_CS_4,
	GSN_IOMUX_GPIO_4_CM3_TRACECLKIN_PREDFT,
	GSN_IOMUX_GPIO_4_CLK_RTC
	
}GSN_IOMUX_GPIO_4;

typedef enum GSN_IOMUX_GPIO_5
{
	GSN_IOMUX_GPIO_5_AGPIO_5,
	GSN_IOMUX_GPIO_5_WGPIO_5,
	GSN_IOMUX_GPIO_5_DEBUG_8,
	GSN_IOMUX_GPIO_5_ASSP1_CLK,
	GSN_IOMUX_GPIO_5_WSSP_CLK,
	GSN_IOMUX_GPIO_5_APWM_0,
	GSN_IOMUX_GPIO_5_CM3_TRACECLK,
	GSN_IOMUX_GPIO_5_ASSP0_CS_3
	
}GSN_IOMUX_GPIO_5;


typedef enum GSN_IOMUX_GPIO_6
{
	GSN_IOMUX_GPIO_6_AGPIO_6,
	GSN_IOMUX_GPIO_6_WGPIO_6,
	GSN_IOMUX_GPIO_6_DEBUG_6,
	GSN_IOMUX_GPIO_6_ASSP1_DIN,
	GSN_IOMUX_GPIO_6_WSSP_DIN,
	GSN_IOMUX_GPIO_6_ASSP1_DOUT,
	GSN_IOMUX_GPIO_6_WSSP_DOUT,
	GSN_IOMUX_GPIO_6_ASSP0_CS_1

}GSN_IOMUX_GPIO_6;

typedef enum GSN_IOMUX_GPIO_7
{

	GSN_IOMUX_GPIO_7_AGPIO_7,
	GSN_IOMUX_GPIO_7_WGPIO_7,
	GSN_IOMUX_GPIO_7_DEBUG_7,
	GSN_IOMUX_GPIO_7_ASSP1_DOUT,
	GSN_IOMUX_GPIO_7_WSSP_DOUT,
	GSN_IOMUX_GPIO_7_ASSP1_DIN,
	GSN_IOMUX_GPIO_7_WSSP_DIN,
	GSN_IOMUX_GPIO_7_ASSP0_CS_02

}GSN_IOMUX_GPIO_7;

typedef enum GSN_IOMUX_GPIO_8
{
	GSN_IOMUX_GPIO_8_AGPIO_8,
	GSN_IOMUX_GPIO_8_WGPIO_8,
	GSN_IOMUX_GPIO_8_DEBUG_1,
	GSN_IOMUX_GPIO_8_AI2C_SDA,
	GSN_IOMUX_GPIO_8_AUART1_TXD,
	GSN_IOMUX_GPIO_8_ASSP1_CS_7,
	GSN_IOMUX_GPIO_8_CM3_TRACEDATA_3,
	GSN_IOMUX_GPIO_8_APWM_0
	
}GSN_IOMUX_GPIO_8;


typedef enum GSN_IOMUX_GPIO_9
{
	GSN_IOMUX_GPIO_9_AGPIO_9,
	GSN_IOMUX_GPIO_9_WGPIO_9,
	GSN_IOMUX_GPIO_9_DEBUG_0,
	GSN_IOMUX_GPIO_9_AI2C_SCL,
	GSN_IOMUX_GPIO_9_AUART1_RXD,
	GSN_IOMUX_GPIO_ASSP1_CS_6,
	GSN_IOMUX_GPIO_9_CM3_TRACEDATA_1,
	GSN_IOMUX_GPIO_9_ASSP1_CLK

}GSN_IOMUX_GPIO_9;


typedef enum GSN_IOMUX_GPIO_10
{
	GSN_IOMUX_GPIO_10_AGPIO_10,
	GSN_IOMUX_GPIO_10_WGPIO_10,
	GSN_IOMUX_GPIO_10_DEBUG_14,
	GSN_IOMUX_GPIO_10_APWM_0,
	GSN_IOMUX_GPIO_10_AUART1_RXD,
	GSN_IOMUX_GPIO_10_CLK_HS_XTAL,
	GSN_IOMUX_GPIO_10_CM3_TRACEDATA_0,
	CM3_TRACEDATA_CLK_RTC
	
}GSN_IOMUX_GPIO_10;


typedef enum GSN_IOMUX_GPIO_11
{
	GSN_IOMUX_GPIO_11_AGPIO_11,
	GSN_IOMUX_GPIO_11_WGPIO_11,
	GSN_IOMUX_GPIO_11_DEBUG_15,
	GSN_IOMUX_GPIO_11_APWM_1,
	GSN_IOMUX_GPIO_11_AUART1_TXD,
	GSN_IOMUX_GPIO_11_ASSP1_CS_5,
	GSN_IOMUX_GPIO_11_ASSP0_CS_9,
	GSN_IOMUX_GPIO_11_WSSP_CS_2,

}GSN_IOMUX_GPIO_11;



typedef enum GSN_IOMUX_GPIO_12
{
	GSN_IOMUX_GPIO_12_AGPIO_12,
	GSN_IOMUX_GPIO_12_WGPIO_12,
	GSN_IOMUX_GPIO_12_DEBUG_2,
	GSN_IOMUX_GPIO_12_AI2S_DOUT,
	GSN_IOMUX_GPIO_12_ASSP0_DOUT,
	GSN_IOMUX_GPIO_12_WSSP_DOUT,
	GSN_IOMUX_GPIO_12_CM3_TRACEDATA_0,
	GSN_IOMUX_GPIO_12_ASSP1_CS_16
	
}GSN_IOMUX_GPIO_12;



typedef enum GSN_IOMUX_GPIO_13
{
	GSN_IOMUX_GPIO_13_AGPIO_13,
	GSN_IOMUX_GPIO_13_WGPIO_13,
	GSN_IOMUX_GPIO_13_DEBUG_10,
	GSN_IOMUX_GPIO_13_ASSP1_CS_1,
	GSN_IOMUX_GPIO_13_APWM_2,
	GSN_IOMUX_GPIO_13_ASSP0_CS_5,
	GSN_IOMUX_GPIO_13_CM3_TRACEDATA_0,
	GSN_IOMUX_GPIO_13_WSSP_CS_1

}GSN_IOMUX_GPIO_13;


typedef enum GSN_IOMUX_GPIO_14
{
	GSN_IOMUX_GPIO_14_AGPIO_14,
	GSN_IOMUX_GPIO_14_WGPIO_14,
	GSN_IOMUX_GPIO_14_DEBUG_3,
	GSN_IOMUX_GPIO_14_AI2S_DIN,
	GSN_IOMUX_GPIO_14_ASSP0_BI_CS,
	GSN_IOMUX_GPIO_14_WSSP_BI_CS,
	GSN_IOMUX_GPIO_14_CM3_TRACEDATA_1,
	GSN_IOMUX_GPIO_14_ASSP1_CS_17
	
}GSN_IOMUX_GPIO_14;


typedef enum GSN_IOMUX_GPIO_15
{
	GSN_IOMUX_GPIO_15_AGPIO_15,
	GSN_IOMUX_GPIO_15_WGPIO_15,
	GSN_IOMUX_GPIO_15_DEBUG_0,
	GSN_IOMUX_GPIO_15_ASSP0_DOUT,
	GSN_IOMUX_GPIO_15_TEST_DOUT,
	GSN_IOMUX_GPIO_15_TEST_DIN,
	GSN_IOMUX_GPIO_15_ASSP0_DIN,
	GSN_IOMUX_GPIO_15_ASSP1_CS_8
	
}GSN_IOMUX_GPIO_15;


typedef enum GSN_IOMUX_GPIO_16
{
	GSN_IOMUX_GPIO_16_AGPIO_16,
	GSN_IOMUX_GPIO_16_WGPIO_16,
	GSN_IOMUX_GPIO_16_DEBUG_1,
	GSN_IOMUX_GPIO_16_ASSP0_CLK,
	GSN_IOMUX_GPIO_16_TEST_CLK_PAD,
	GSN_IOMUX_GPIO_16_AUART1_RXD,
	GSN_IOMUX_GPIO_16_WUART_RXD,
	GSN_IOMUX_GPIO_16_ASSP1_CS_9

}GSN_IOMUX_GPIO_16;



typedef enum GSN_IOMUX_GPIO_17
{
	GSN_IOMUX_GPIO_17_AGPIO_17,
	GSN_IOMUX_GPIO_17_WGPIO_17,
	GSN_IOMUX_GPIO_17_DEBUG_28,
	GSN_IOMUX_GPIO_17_ASSP0_BI_CS,
	GSN_IOMUX_GPIO_17_TEST_CS_N_PAD,
	GSN_IOMUX_GPIO_17_AUART1_TXD,
	GSN_IOMUX_GPIO_17_WUART_TXD,
	GSN_IOMUX_GPIO_17_ASSP1_CS_10

}GSN_IOMUX_GPIO_17;


typedef enum GSN_IOMUX_GPIO_18
{
	GSN_IOMUX_GPIO_18_AGPIO_18,
	GSN_IOMUX_GPIO_18_WGPIO_18,
	GSN_IOMUX_GPIO_18_DEBUG_29,
	GSN_IOMUX_GPIO_18_ASSP0_DIN,
	GSN_IOMUX_GPIO_18_TEST_DIN,
	GSN_IOMUX_GPIO_18_TEST_DOUT,
	GSN_IOMUX_GPIO_18_ASSP0_DOUT,
	GSN_IOMUX_GPIO_18_ASSP1_CS_11

}GSN_IOMUX_GPIO_18;


typedef enum GSN_IOMUX_GPIO_19
{
	GSN_IOMUX_GPIO_19_AGPIO_19,
	GSN_IOMUX_GPIO_19_WGPIO_19,
	GSN_IOMUX_GPIO_19_DEBUG_13,
	GSN_IOMUX_GPIO_19_CLK_HS_XTAL,
	GSN_IOMUX_GPIO_19_ASSP1_CS_4,
	GSN_IOMUX_GPIO_19_APWM_2,
	GSN_IOMUX_GPIO_19_CM3_TRACEDATA_3,
	GSN_IOMUX_GPIO_19_ASSP0_CS_8

}GSN_IOMUX_GPIO_19;


typedef enum GSN_IOMUX_GPIO_20
{
	GSN_IOMUX_GPIO_20_AGPIO_20,
	GSN_IOMUX_GPIO_20_WGPIO_20,
	GSN_IOMUX_GPIO_20_DEBUG_12,
	GSN_IOMUX_GPIO_20_CLK_HS_RC,
	GSN_IOMUX_GPIO_20_ASSP1_CS_3,
	GSN_IOMUX_GPIO_20_CLK_HS_XTAL,
	GSN_IOMUX_GPIO_20_CM3_TRACEDATA_2,
	GSN_IOMUX_GPIO_20_ASSP0_CS_7

}GSN_IOMUX_GPIO_20;



typedef enum GSN_IOMUX_GPIO_21
{
	GSN_IOMUX_GPIO_21_AGPIO_21,
	GSN_IOMUX_GPIO_21_WGPIO_21,
	GSN_IOMUX_GPIO_21_DEBUG_11,
	GSN_IOMUX_GPIO_21_CLK_RTC,
	GSN_IOMUX_GPIO_21_ASSP1_CS_2,
	GSN_IOMUX_GPIO_21_CLK_HS_XTAL,
	GSN_IOMUX_GPIO_21_CM3_TRACEDATA_1,
	GSN_IOMUX_GPIO_21_ASSP0_CS_6

}GSN_IOMUX_GPIO_21;



typedef enum GSN_IOMUX_GPIO_22
{
	GSN_IOMUX_GPIO_22_AGPIO_22,
	GSN_IOMUX_GPIO_22_WGPIO_22,
	GSN_IOMUX_GPIO_22_DEBUG_4,
	GSN_IOMUX_GPIO_22_AI2S_BITCLK,
	GSN_IOMUX_GPIO_22_ASSP0_CLK,
	GSN_IOMUX_GPIO_22_WSSP_CLK,
	GSN_IOMUX_GPIO_22_CM3_TRACEDATA_2,
	GSN_IOMUX_GPIO_ASSP1_CS_18

}GSN_IOMUX_GPIO_22;


typedef enum GSN_IOMUX_GPIO_23
{
	GSN_IOMUX_GPIO_23_AGPIO_23,
	GSN_IOMUX_GPIO_23_WGPIO_23,
	GSN_IOMUX_GPIO_23_DEBUG_5,
	GSN_IOMUX_GPIO_23_I2S_LRCLK,
	GSN_IOMUX_GPIO_23_ASSP0_DIN,
	GSN_IOMUX_GPIO_23_WSSP_DIN,
	GSN_IOMUX_GPIO_23_CM3_TRACEDATA_3,
	GSN_IOMUX_GPIO_23_ASSP1_CS_19

}GSN_IOMUX_GPIO_23;


typedef enum GSN_IOMUX_GPIO_24
{
	GSN_IOMUX_GPIO_24_AGPIO_24,
	GSN_IOMUX_GPIO_24_WGPIO_24,
	GSN_IOMUX_GPIO_24_SDIO_PULLUP_EN,
	GSN_IOMUX_GPIO_24_AUART0_CTS_N,
	GSN_IOMUX_GPIO_24_WUART_CTS_N,
	GSN_IOMUX_GPIO_24_AI2C_SCL,
	GSN_IOMUX_GPIO_24_CM3_TRACEDATA_3,
	GSN_IOMUX_GPIO_24_ASSP1_BI_CS

}GSN_IOMUX_GPIO_24;

typedef enum GSN_IOMUX_GPIO_25
{
	GSN_IOMUX_GPIO_25_AGPIO_25,
	GSN_IOMUX_GPIO_25_WGPIO_25,
	GSN_IOMUX_GPIO_25_SDIO_PULLUP_EN,
	GSN_IOMUX_GPIO_25_AUART0_RTS_N,
	GSN_IOMUX_GPIO_25_WUART_RTS_N,
	GSN_IOMUX_GPIO_25_AI2C_SDA,
	GSN_IOMUX_GPIO_25_CM3_TRACEDATA_1,
	GSN_IOMUX_GPIO_25_ASSP1_CLK

}GSN_IOMUX_GPIO_25;

typedef enum GSN_IOMUX_GPIO_26
{
	GSN_IOMUX_GPIO_26_AGPIO_26,
	GSN_IOMUX_GPIO_26_WGPIO_26,
	GSN_IOMUX_GPIO_26_DEBUG_16,
	GSN_IOMUX_GPIO_26_AUART1_CTS_N,
	GSN_IOMUX_GPIO_26_WUART_CTS_N,
	GSN_IOMUX_GPIO_26_AI2S_DIN,
	GSN_IOMUX_GPIO_26_ASSP1_CS_13,
	GSN_IOMUX_GPIO_26_WSSP_CLK

}GSN_IOMUX_GPIO_26;
	
	

typedef enum GSN_IOMUX_GPIO_27
{
	GSN_IOMUX_GPIO_27_AGPIO_27,
	GSN_IOMUX_GPIO_27_WGPIO_27,
	GSN_IOMUX_GPIO_27_DEBUG_17,
	GSN_IOMUX_GPIO_27_AUART1_RTS_N,
	GSN_IOMUX_GPIO_27_WUART_RTS_N,
	GSN_IOMUX_GPIO_27_AI2S_DOUT,
	GSN_IOMUX_GPIO_27_AUART1_TXD,
	GSN_IOMUX_GPIO_27_WSSP_DOUT

}GSN_IOMUX_GPIO_27;



typedef enum GSN_IOMUX_GPIO_28
{
	GSN_IOMUX_GPIO_28_AGPIO_28,
	GSN_IOMUX_GPIO_28_WGPIO_28,
	GSN_IOMUX_GPIO_28_DEBUG_31,
	GSN_IOMUX_GPIO_28_AI2C_SDA,
	GSN_IOMUX_GPIO_28_ASSP1_CLK,
	GSN_IOMUX_GPIO_28_CLK_HS_RC,
	GSN_IOMUX_GPIO_28_CM3_TRACEDATA_2,
	GSN_IOMUX_GPIO_28_ASSP1_CS_21

}GSN_IOMUX_GPIO_28;


typedef enum GSN_IOMUX_GPIO_29
{
	GSN_IOMUX_GPIO_29_AGPIO_29,
	GSN_IOMUX_GPIO_29_WGPIO_29,
	GSN_IOMUX_GPIO_29_DEBUG_30,
	GSN_IOMUX_GPIO_29_AI2C_SCL,
	GSN_IOMUX_GPIO_29_ASSP1_CS_20,
	GSN_IOMUX_GPIO_29_CLK_RTC,
	GSN_IOMUX_GPIO_29_CM3_TRACEDATA_0,
	GSN_IOMUX_GPIO_29_APWM_0

}GSN_IOMUX_GPIO_29;
		

typedef enum GSN_IOMUX_GPIO_30
{
	GSN_IOMUX_GPIO_30_AGPIO_30,
	GSN_IOMUX_GPIO_30_WGPIO_30,
	GSN_IOMUX_GPIO_30_24730TX_SYNC_CLK,
	GSN_IOMUX_GPIO_30_APWM_1,
	GSN_IOMUX_GPIO_30_ASSP1_DIN,
	GSN_IOMUX_GPIO_30_AUART1_RXD,
	GSN_IOMUX_GPIO_30_CM3_TRACECLKIN_PREDFT,
	GSN_IOMUX_GPIO_30_WUART_RXD

}GSN_IOMUX_GPIO_30;


typedef enum GSN_IOMUX_GPIO_31
{
	GSN_IOMUX_GPIO_31_AGPIO_31,
	GSN_IOMUX_GPIO_31_WGPIO_31,
	GSN_IOMUX_GPIO_31_24730TX_SYNC_PULSE,
	GSN_IOMUX_GPIO_31_APWM_2,
	GSN_IOMUX_GPIO_31_ASSP1_DOUT,
	GSN_IOMUX_GPIO_31_AUART1_TXD,
	GSN_IOMUX_GPIO_31_CM3_TRACECLK,
	GSN_IOMUX_GPIO_31_WUART_TXD

}GSN_IOMUX_GPIO_31;


typedef enum GSN_IOMUX_GPIO_32
{
	GSN_IOMUX_GPIO_32_AGPIO_32,
	GSN_IOMUX_GPIO_32_WGPIO_32,
	GSN_IOMUX_GPIO_32_DEBUG_22,
	GSN_IOMUX_GPIO_32_SDIO_DATA2,
	GSN_IOMUX_GPIO_32_WUART_TXD,
	GSN_IOMUX_GPIO_32_AUART1_TXD,
	GSN_IOMUX_GPIO_32_CM3_TRACEDATA_2,
	GSN_IOMUX_GPIO_32_ASSP1_CS_12

}GSN_IOMUX_GPIO_32;

typedef enum GSN_IOMUX_GPIO_33
{
	GSN_IOMUX_GPIO_33_AGPIO_33,
	GSN_IOMUX_GPIO_33_WGPIO_33,
	GSN_IOMUX_GPIO_33_DEBUG_23,
	GSN_IOMUX_GPIO_33_SDIO_DATA3,
	GSN_IOMUX_GPIO_33_TEST_CS_N_PAD,
	GSN_IOMUX_GPIO_33_AUART1_RTS_N,
	GSN_IOMUX_GPIO_33_CM3_TRACEDATA_0,
	GSN_IOMUX_GPIO_33_ASSP0_BI_CS

}GSN_IOMUX_GPIO_33;


typedef enum GSN_IOMUX_GPIO_34
{
	GSN_IOMUX_GPIO_34_AGPIO_34,
	GSN_IOMUX_GPIO_34_WGPIO_34,
	GSN_IOMUX_GPIO_34_DEBUG_24,
	GSN_IOMUX_GPIO_34_SDIO_CMD,
	GSN_IOMUX_GPIO_34_TEST_DIN,
	GSN_IOMUX_GPIO_34_AUART1_CTS_N,
	GSN_IOMUX_GPIO_34_CM3_TRACEDATA_1,
	GSN_IOMUX_GPIO_34_ASSP0_DIN

}GSN_IOMUX_GPIO_34;


typedef enum GSN_IOMUX_GPIO_35
{
	GSN_IOMUX_GPIO_35_AGPIO_35,
	GSN_IOMUX_GPIO_35_WGPIO_35,
	GSN_IOMUX_GPIO_35_DEBUG_25,
	GSN_IOMUX_GPIO_35_CLK_SDIO_PAD,
	GSN_IOMUX_GPIO_35_TEST_CLK_PAD,
	GSN_IOMUX_GPIO_35_AI2C_SCL,
	GSN_IOMUX_GPIO_35_CM3_TRACECLK,
	GSN_IOMUX_GPIO_35_ASSP0_CLK

}GSN_IOMUX_GPIO_35;


typedef enum GSN_IOMUX_GPIO_36
{
	GSN_IOMUX_GPIO_36_AGPIO_36,
	GSN_IOMUX_GPIO_36_WGPIO_36,
	GSN_IOMUX_GPIO_36_DEBUG_26,
	GSN_IOMUX_GPIO_36_SDIO_DATA0,
	GSN_IOMUX_GPIO_36_TEST_DOUT,
	GSN_IOMUX_GPIO_36_AI2C_SDA,
	GSN_IOMUX_GPIO_36_CM3_TRACECLKIN_PREDFT,
	GSN_IOMUX_GPIO_36_ASSP0_DOUT

}GSN_IOMUX_GPIO_36;



typedef enum GSN_IOMUX_GPIO_37
{
	GSN_IOMUX_GPIO_37_AGPIO_37,
	GSN_IOMUX_GPIO_37_WGPIO_36,
	GSN_IOMUX_GPIO_37_DEBUG_27,
	GSN_IOMUX_GPIO_37_SDIO_DATA1,
	GSN_IOMUX_GPIO_37_WUART_RXD,
	GSN_IOMUX_GPIO_37_AUART1_RXD,
	GSN_IOMUX_GPIO_37_CM3_TRACEDATA_3,
	GSN_IOMUX_GPIO_37_ASSP0_CS_10

}GSN_IOMUX_GPIO_37;



#ifdef __cplusplus
}
#endif
#endif
